// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countActiveAPIKeys = `-- name: CountActiveAPIKeys :one
SELECT COUNT(*) FROM api_keys WHERE org_id = $1 AND revoked_at IS NULL
`

func (q *Queries) CountActiveAPIKeys(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeys, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (org_id, key_hash, key_prefix, label)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, key_hash, key_prefix, label, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	OrgID     uuid.UUID `json:"org_id"`
	KeyHash   string    `json:"key_hash"`
	KeyPrefix string    `json:"key_prefix"`
	Label     string    `json:"label"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.OrgID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Label,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, org_id, key_hash, key_prefix, label, created_at, last_used_at, revoked_at FROM api_keys WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, org_id, key_hash, key_prefix, label, created_at, last_used_at, revoked_at FROM api_keys WHERE org_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC LIMIT 200
`

func (q *Queries) ListAPIKeys(ctx context.Context, orgID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = NOW() WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.OrgID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
