// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgMonitors = `-- name: CountOrgMonitors :one
SELECT
    (SELECT COUNT(*) FROM cron_monitors WHERE cron_monitors.org_id = $1)::int +
    (SELECT COUNT(*) FROM uptime_monitors WHERE uptime_monitors.org_id = $1)::int +
    (SELECT COUNT(*) FROM ssl_monitors WHERE ssl_monitors.org_id = $1)::int AS total
`

func (q *Queries) CountOrgMonitors(ctx context.Context, orgID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgMonitors, orgID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countOrgStatusPages = `-- name: CountOrgStatusPages :one
SELECT COUNT(*)::int AS total FROM status_pages WHERE org_id = $1
`

func (q *Queries) CountOrgStatusPages(ctx context.Context, orgID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgStatusPages, orgID)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const getOrgBillingInfo = `-- name: GetOrgBillingInfo :one
SELECT
    o.plan,
    o.billing_cycle,
    o.ls_customer_id,
    o.ls_subscription_id,
    o.subscription_status,
    o.plan_renews_at,
    (
        (SELECT COUNT(*) FROM cron_monitors WHERE org_id = o.id)::int +
        (SELECT COUNT(*) FROM uptime_monitors WHERE org_id = o.id)::int +
        (SELECT COUNT(*) FROM ssl_monitors WHERE org_id = o.id)::int
    ) AS monitor_count,
    (SELECT COUNT(*) FROM status_pages WHERE org_id = o.id)::int AS status_page_count
FROM orgs o
WHERE o.id = $1
`

type GetOrgBillingInfoRow struct {
	Plan               Plan               `json:"plan"`
	BillingCycle       string             `json:"billing_cycle"`
	LsCustomerID       pgtype.Text        `json:"ls_customer_id"`
	LsSubscriptionID   pgtype.Text        `json:"ls_subscription_id"`
	SubscriptionStatus string             `json:"subscription_status"`
	PlanRenewsAt       pgtype.Timestamptz `json:"plan_renews_at"`
	MonitorCount       int32              `json:"monitor_count"`
	StatusPageCount    int32              `json:"status_page_count"`
}

func (q *Queries) GetOrgBillingInfo(ctx context.Context, id uuid.UUID) (GetOrgBillingInfoRow, error) {
	row := q.db.QueryRow(ctx, getOrgBillingInfo, id)
	var i GetOrgBillingInfoRow
	err := row.Scan(
		&i.Plan,
		&i.BillingCycle,
		&i.LsCustomerID,
		&i.LsSubscriptionID,
		&i.SubscriptionStatus,
		&i.PlanRenewsAt,
		&i.MonitorCount,
		&i.StatusPageCount,
	)
	return i, err
}

const getOrgPlan = `-- name: GetOrgPlan :one
SELECT plan FROM orgs WHERE id = $1
`

func (q *Queries) GetOrgPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getOrgPlan, id)
	var plan Plan
	err := row.Scan(&plan)
	return plan, err
}

const updateOrgPlan = `-- name: UpdateOrgPlan :exec
UPDATE orgs
SET
    plan                = $2,
    billing_cycle        = $3,
    ls_customer_id      = $4,
    ls_subscription_id  = $5,
    subscription_status = $6,
    plan_renews_at      = $7,
    updated_at          = NOW()
WHERE id = $1
`

type UpdateOrgPlanParams struct {
	ID                 uuid.UUID          `json:"id"`
	Plan               Plan               `json:"plan"`
	BillingCycle       string             `json:"billing_cycle"`
	LsCustomerID       pgtype.Text        `json:"ls_customer_id"`
	LsSubscriptionID   pgtype.Text        `json:"ls_subscription_id"`
	SubscriptionStatus string             `json:"subscription_status"`
	PlanRenewsAt       pgtype.Timestamptz `json:"plan_renews_at"`
}

func (q *Queries) UpdateOrgPlan(ctx context.Context, arg UpdateOrgPlanParams) error {
	_, err := q.db.Exec(ctx, updateOrgPlan,
		arg.ID,
		arg.Plan,
		arg.BillingCycle,
		arg.LsCustomerID,
		arg.LsSubscriptionID,
		arg.SubscriptionStatus,
		arg.PlanRenewsAt,
	)
	return err
}
