// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDNSCheck = `-- name: CreateDNSCheck :one
INSERT INTO dns_checks (monitor_id, response_time_ms, is_up, resolved_value, failure_reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, monitor_id, checked_at, response_time_ms, is_up, resolved_value, failure_reason
`

type CreateDNSCheckParams struct {
	MonitorID      uuid.UUID   `json:"monitor_id"`
	ResponseTimeMs int32       `json:"response_time_ms"`
	IsUp           bool        `json:"is_up"`
	ResolvedValue  pgtype.Text `json:"resolved_value"`
	FailureReason  pgtype.Text `json:"failure_reason"`
}

func (q *Queries) CreateDNSCheck(ctx context.Context, arg CreateDNSCheckParams) (DnsCheck, error) {
	row := q.db.QueryRow(ctx, createDNSCheck,
		arg.MonitorID,
		arg.ResponseTimeMs,
		arg.IsUp,
		arg.ResolvedValue,
		arg.FailureReason,
	)
	var i DnsCheck
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.CheckedAt,
		&i.ResponseTimeMs,
		&i.IsUp,
		&i.ResolvedValue,
		&i.FailureReason,
	)
	return i, err
}

const createDNSIncident = `-- name: CreateDNSIncident :one
INSERT INTO dns_incidents (monitor_id) VALUES ($1) RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) CreateDNSIncident(ctx context.Context, monitorID uuid.UUID) (DnsIncident, error) {
	row := q.db.QueryRow(ctx, createDNSIncident, monitorID)
	var i DnsIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const createDNSMonitor = `-- name: CreateDNSMonitor :one
INSERT INTO dns_monitors (org_id, name, hostname, record_type, expected_value, interval_mins, max_alerts_per_incident, alert_after_n_failures)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type CreateDNSMonitorParams struct {
	OrgID                uuid.UUID     `json:"org_id"`
	Name                 string        `json:"name"`
	Hostname             string        `json:"hostname"`
	RecordType           DnsRecordType `json:"record_type"`
	ExpectedValue        pgtype.Text   `json:"expected_value"`
	IntervalMins         int32         `json:"interval_mins"`
	MaxAlertsPerIncident int32         `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32         `json:"alert_after_n_failures"`
}

func (q *Queries) CreateDNSMonitor(ctx context.Context, arg CreateDNSMonitorParams) (DnsMonitor, error) {
	row := q.db.QueryRow(ctx, createDNSMonitor,
		arg.OrgID,
		arg.Name,
		arg.Hostname,
		arg.RecordType,
		arg.ExpectedValue,
		arg.IntervalMins,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
	)
	var i DnsMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.RecordType,
		&i.ExpectedValue,
		&i.BaselineCaptured,
		&i.LastResolvedValue,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDNSMonitor = `-- name: DeleteDNSMonitor :exec
DELETE FROM dns_monitors WHERE id = $1 AND org_id = $2
`

type DeleteDNSMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteDNSMonitor(ctx context.Context, arg DeleteDNSMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteDNSMonitor, arg.ID, arg.OrgID)
	return err
}

const deleteOldDNSChecks = `-- name: DeleteOldDNSChecks :exec
DELETE FROM dns_checks WHERE checked_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) DeleteOldDNSChecks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldDNSChecks)
	return err
}

const getDNSDailyStatus90d = `-- name: GetDNSDailyStatus90d :many
SELECT
    date_trunc('day', checked_at AT TIME ZONE 'UTC')::date AS day,
    COUNT(*) FILTER (WHERE NOT is_up)                       AS down_count
FROM dns_checks
WHERE monitor_id = $1 AND checked_at >= NOW() - INTERVAL '90 days'
GROUP BY 1
`

type GetDNSDailyStatus90dRow struct {
	Day       pgtype.Date `json:"day"`
	DownCount int64       `json:"down_count"`
}

func (q *Queries) GetDNSDailyStatus90d(ctx context.Context, monitorID uuid.UUID) ([]GetDNSDailyStatus90dRow, error) {
	rows, err := q.db.Query(ctx, getDNSDailyStatus90d, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDNSDailyStatus90dRow{}
	for rows.Next() {
		var i GetDNSDailyStatus90dRow
		if err := rows.Scan(&i.Day, &i.DownCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDNSMonitor = `-- name: GetDNSMonitor :one
SELECT id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at FROM dns_monitors WHERE id = $1 AND org_id = $2
`

type GetDNSMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDNSMonitor(ctx context.Context, arg GetDNSMonitorParams) (DnsMonitor, error) {
	row := q.db.QueryRow(ctx, getDNSMonitor, arg.ID, arg.OrgID)
	var i DnsMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.RecordType,
		&i.ExpectedValue,
		&i.BaselineCaptured,
		&i.LastResolvedValue,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSMonitorPublic = `-- name: GetDNSMonitorPublic :one
SELECT id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at FROM dns_monitors WHERE id = $1
`

func (q *Queries) GetDNSMonitorPublic(ctx context.Context, id uuid.UUID) (DnsMonitor, error) {
	row := q.db.QueryRow(ctx, getDNSMonitorPublic, id)
	var i DnsMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.RecordType,
		&i.ExpectedValue,
		&i.BaselineCaptured,
		&i.LastResolvedValue,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDNSStats = `-- name: GetDNSStats :one
SELECT
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '24 hours')  AS up_24h,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '24 hours')             AS total_24h,
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '7 days')    AS up_7d,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '7 days')               AS total_7d,
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '30 days')   AS up_30d,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '30 days')              AS total_30d
FROM dns_checks
WHERE monitor_id = $1
`

type GetDNSStatsRow struct {
	Up24h    int64 `json:"up_24h"`
	Total24h int64 `json:"total_24h"`
	Up7d     int64 `json:"up_7d"`
	Total7d  int64 `json:"total_7d"`
	Up30d    int64 `json:"up_30d"`
	Total30d int64 `json:"total_30d"`
}

func (q *Queries) GetDNSStats(ctx context.Context, monitorID uuid.UUID) (GetDNSStatsRow, error) {
	row := q.db.QueryRow(ctx, getDNSStats, monitorID)
	var i GetDNSStatsRow
	err := row.Scan(
		&i.Up24h,
		&i.Total24h,
		&i.Up7d,
		&i.Total7d,
		&i.Up30d,
		&i.Total30d,
	)
	return i, err
}

const incrementDNSIncidentAlertCount = `-- name: IncrementDNSIncidentAlertCount :one
UPDATE dns_incidents SET alert_count = alert_count + 1 WHERE id = $1 RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) IncrementDNSIncidentAlertCount(ctx context.Context, id uuid.UUID) (DnsIncident, error) {
	row := q.db.QueryRow(ctx, incrementDNSIncidentAlertCount, id)
	var i DnsIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const listDNSChecks = `-- name: ListDNSChecks :many
SELECT id, monitor_id, checked_at, response_time_ms, is_up, resolved_value, failure_reason FROM dns_checks WHERE monitor_id = $1 ORDER BY checked_at DESC LIMIT $2 OFFSET $3
`

type ListDNSChecksParams struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListDNSChecks(ctx context.Context, arg ListDNSChecksParams) ([]DnsCheck, error) {
	rows, err := q.db.Query(ctx, listDNSChecks, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsCheck{}
	for rows.Next() {
		var i DnsCheck
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.CheckedAt,
			&i.ResponseTimeMs,
			&i.IsUp,
			&i.ResolvedValue,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSChecks24h = `-- name: ListDNSChecks24h :many
SELECT id, monitor_id, checked_at, response_time_ms, is_up, resolved_value, failure_reason FROM dns_checks
WHERE monitor_id = $1 AND checked_at >= NOW() - INTERVAL '24 hours'
ORDER BY checked_at ASC
`

func (q *Queries) ListDNSChecks24h(ctx context.Context, monitorID uuid.UUID) ([]DnsCheck, error) {
	rows, err := q.db.Query(ctx, listDNSChecks24h, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsCheck{}
	for rows.Next() {
		var i DnsCheck
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.CheckedAt,
			&i.ResponseTimeMs,
			&i.IsUp,
			&i.ResolvedValue,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSIncidents = `-- name: ListDNSIncidents :many
SELECT id, monitor_id, started_at, resolved_at, alert_count FROM dns_incidents WHERE monitor_id = $1 ORDER BY started_at DESC LIMIT 200
`

func (q *Queries) ListDNSIncidents(ctx context.Context, monitorID uuid.UUID) ([]DnsIncident, error) {
	rows, err := q.db.Query(ctx, listDNSIncidents, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsIncident{}
	for rows.Next() {
		var i DnsIncident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AlertCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDNSMonitors = `-- name: ListDNSMonitors :many
SELECT id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at FROM dns_monitors WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDNSMonitors(ctx context.Context, orgID uuid.UUID) ([]DnsMonitor, error) {
	rows, err := q.db.Query(ctx, listDNSMonitors, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsMonitor{}
	for rows.Next() {
		var i DnsMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Hostname,
			&i.RecordType,
			&i.ExpectedValue,
			&i.BaselineCaptured,
			&i.LastResolvedValue,
			&i.IntervalMins,
			&i.Status,
			&i.AlertsEnabled,
			&i.MaxAlertsPerIncident,
			&i.AlertAfterNFailures,
			&i.ConsecutiveFailures,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDNSMonitors = `-- name: ListDueDNSMonitors :many
SELECT id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at FROM dns_monitors
WHERE next_check_at <= NOW() AND status != 'paused'
  AND NOT EXISTS (
    SELECT 1 FROM maintenance_window_monitors mwm
    JOIN maintenance_windows mw ON mw.id = mwm.window_id
    WHERE mwm.monitor_type = 'dns' AND mwm.monitor_id = dns_monitors.id
      AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
  )
`

func (q *Queries) ListDueDNSMonitors(ctx context.Context) ([]DnsMonitor, error) {
	rows, err := q.db.Query(ctx, listDueDNSMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsMonitor{}
	for rows.Next() {
		var i DnsMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Hostname,
			&i.RecordType,
			&i.ExpectedValue,
			&i.BaselineCaptured,
			&i.LastResolvedValue,
			&i.IntervalMins,
			&i.Status,
			&i.AlertsEnabled,
			&i.MaxAlertsPerIncident,
			&i.AlertAfterNFailures,
			&i.ConsecutiveFailures,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDNSMonitorDown = `-- name: MarkDNSMonitorDown :exec
UPDATE dns_monitors SET status = 'down', updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkDNSMonitorDown(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDNSMonitorDown, id)
	return err
}

const pauseDNSMonitor = `-- name: PauseDNSMonitor :one
UPDATE dns_monitors SET status = 'paused', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type PauseDNSMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) PauseDNSMonitor(ctx context.Context, arg PauseDNSMonitorParams) (DnsMonitor, error) {
	row := q.db.QueryRow(ctx, pauseDNSMonitor, arg.ID, arg.OrgID)
	var i DnsMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.RecordType,
		&i.ExpectedValue,
		&i.BaselineCaptured,
		&i.LastResolvedValue,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordDNSCheckFailure = `-- name: RecordDNSCheckFailure :one
UPDATE dns_monitors
SET consecutive_failures = consecutive_failures + 1,
    last_checked_at = NOW(),
    next_check_at = NOW() + (interval_mins * INTERVAL '1 minute'),
    last_resolved_value = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type RecordDNSCheckFailureParams struct {
	ID                uuid.UUID   `json:"id"`
	LastResolvedValue pgtype.Text `json:"last_resolved_value"`
}

func (q *Queries) RecordDNSCheckFailure(ctx context.Context, arg RecordDNSCheckFailureParams) (DnsMonitor, error) {
	row := q.db.QueryRow(ctx, recordDNSCheckFailure, arg.ID, arg.LastResolvedValue)
	var i DnsMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.RecordType,
		&i.ExpectedValue,
		&i.BaselineCaptured,
		&i.LastResolvedValue,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordDNSCheckUp = `-- name: RecordDNSCheckUp :one
UPDATE dns_monitors
SET status = 'up',
    consecutive_failures = 0,
    last_checked_at = NOW(),
    next_check_at = NOW() + (interval_mins * INTERVAL '1 minute'),
    last_resolved_value = $2,
    expected_value = COALESCE(expected_value, $2),
    baseline_captured = (expected_value IS NULL),
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type RecordDNSCheckUpParams struct {
	ID                uuid.UUID   `json:"id"`
	LastResolvedValue pgtype.Text `json:"last_resolved_value"`
}

// expected_value/baseline_captured only change the first time (COALESCE is
// a no-op once expected_value is already set) — this is where a baseline
// monitor's first successful lookup gets pinned as its comparison value.
func (q *Queries) RecordDNSCheckUp(ctx context.Context, arg RecordDNSCheckUpParams) (DnsMonitor, error) {
	row := q.db.QueryRow(ctx, recordDNSCheckUp, arg.ID, arg.LastResolvedValue)
	var i DnsMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.RecordType,
		&i.ExpectedValue,
		&i.BaselineCaptured,
		&i.LastResolvedValue,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveLatestDNSIncident = `-- name: ResolveLatestDNSIncident :one
UPDATE dns_incidents
SET resolved_at = NOW()
WHERE id = (
    SELECT di.id FROM dns_incidents di
    WHERE di.monitor_id = $1 AND di.resolved_at IS NULL
    ORDER BY di.started_at DESC
    LIMIT 1
)
RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) ResolveLatestDNSIncident(ctx context.Context, monitorID uuid.UUID) (DnsIncident, error) {
	row := q.db.QueryRow(ctx, resolveLatestDNSIncident, monitorID)
	var i DnsIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const resumeDNSMonitor = `-- name: ResumeDNSMonitor :one
UPDATE dns_monitors SET status = 'waiting', next_check_at = NOW(), updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type ResumeDNSMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) ResumeDNSMonitor(ctx context.Context, arg ResumeDNSMonitorParams) (DnsMonitor, error) {
	row := q.db.QueryRow(ctx, resumeDNSMonitor, arg.ID, arg.OrgID)
	var i DnsMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.RecordType,
		&i.ExpectedValue,
		&i.BaselineCaptured,
		&i.LastResolvedValue,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDNSMonitor = `-- name: UpdateDNSMonitor :one
UPDATE dns_monitors
SET name = $3, hostname = $4, record_type = $5, expected_value = $6, baseline_captured = FALSE,
    interval_mins = $7, alerts_enabled = $8, max_alerts_per_incident = $9, alert_after_n_failures = $10,
    updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, hostname, record_type, expected_value, baseline_captured, last_resolved_value, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type UpdateDNSMonitorParams struct {
	ID                   uuid.UUID     `json:"id"`
	OrgID                uuid.UUID     `json:"org_id"`
	Name                 string        `json:"name"`
	Hostname             string        `json:"hostname"`
	RecordType           DnsRecordType `json:"record_type"`
	ExpectedValue        pgtype.Text   `json:"expected_value"`
	IntervalMins         int32         `json:"interval_mins"`
	AlertsEnabled        bool          `json:"alerts_enabled"`
	MaxAlertsPerIncident int32         `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32         `json:"alert_after_n_failures"`
}

// baseline_captured is unconditionally reset to false: an explicit edit
// either pins a user-typed value (not a baseline) or clears it back to
// NULL (baseline not yet re-captured) — either way the prior "auto-captured"
// flag no longer applies. The next successful check re-captures it if the
// value is NULL (RecordDNSCheckUp's COALESCE), same as at creation.
func (q *Queries) UpdateDNSMonitor(ctx context.Context, arg UpdateDNSMonitorParams) (DnsMonitor, error) {
	row := q.db.QueryRow(ctx, updateDNSMonitor,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Hostname,
		arg.RecordType,
		arg.ExpectedValue,
		arg.IntervalMins,
		arg.AlertsEnabled,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
	)
	var i DnsMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.RecordType,
		&i.ExpectedValue,
		&i.BaselineCaptured,
		&i.LastResolvedValue,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
