// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDomainMonitor = `-- name: CreateDomainMonitor :one
INSERT INTO domain_monitors (org_id, name, domain)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type CreateDomainMonitorParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Name   string    `json:"name"`
	Domain string    `json:"domain"`
}

func (q *Queries) CreateDomainMonitor(ctx context.Context, arg CreateDomainMonitorParams) (DomainMonitor, error) {
	row := q.db.QueryRow(ctx, createDomainMonitor, arg.OrgID, arg.Name, arg.Domain)
	var i DomainMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Registrar,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomainMonitor = `-- name: DeleteDomainMonitor :exec
DELETE FROM domain_monitors WHERE id = $1 AND org_id = $2
`

type DeleteDomainMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteDomainMonitor(ctx context.Context, arg DeleteDomainMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteDomainMonitor, arg.ID, arg.OrgID)
	return err
}

const getDomainMonitor = `-- name: GetDomainMonitor :one
SELECT id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at FROM domain_monitors WHERE id = $1 AND org_id = $2
`

type GetDomainMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDomainMonitor(ctx context.Context, arg GetDomainMonitorParams) (DomainMonitor, error) {
	row := q.db.QueryRow(ctx, getDomainMonitor, arg.ID, arg.OrgID)
	var i DomainMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Registrar,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomainMonitors = `-- name: ListDomainMonitors :many
SELECT id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at FROM domain_monitors WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDomainMonitors(ctx context.Context, orgID uuid.UUID) ([]DomainMonitor, error) {
	rows, err := q.db.Query(ctx, listDomainMonitors, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainMonitor{}
	for rows.Next() {
		var i DomainMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Domain,
			&i.Status,
			&i.AlertsEnabled,
			&i.ExpiresAt,
			&i.Registrar,
			&i.ErrorMsg,
			&i.Alerted30d,
			&i.Alerted14d,
			&i.Alerted7d,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueDomainMonitors = `-- name: ListDueDomainMonitors :many
SELECT id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at FROM domain_monitors
WHERE next_check_at <= NOW() AND status != 'paused'
  AND NOT EXISTS (
    SELECT 1 FROM maintenance_window_monitors mwm
    JOIN maintenance_windows mw ON mw.id = mwm.window_id
    WHERE mwm.monitor_type = 'domain' AND mwm.monitor_id = domain_monitors.id
      AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
  )
`

func (q *Queries) ListDueDomainMonitors(ctx context.Context) ([]DomainMonitor, error) {
	rows, err := q.db.Query(ctx, listDueDomainMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainMonitor{}
	for rows.Next() {
		var i DomainMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Domain,
			&i.Status,
			&i.AlertsEnabled,
			&i.ExpiresAt,
			&i.Registrar,
			&i.ErrorMsg,
			&i.Alerted30d,
			&i.Alerted14d,
			&i.Alerted7d,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseDomainMonitor = `-- name: PauseDomainMonitor :one
UPDATE domain_monitors SET status = 'paused', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type PauseDomainMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) PauseDomainMonitor(ctx context.Context, arg PauseDomainMonitorParams) (DomainMonitor, error) {
	row := q.db.QueryRow(ctx, pauseDomainMonitor, arg.ID, arg.OrgID)
	var i DomainMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Registrar,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeDomainMonitor = `-- name: ResumeDomainMonitor :one
UPDATE domain_monitors SET status = 'waiting', next_check_at = NOW(), updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type ResumeDomainMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) ResumeDomainMonitor(ctx context.Context, arg ResumeDomainMonitorParams) (DomainMonitor, error) {
	row := q.db.QueryRow(ctx, resumeDomainMonitor, arg.ID, arg.OrgID)
	var i DomainMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Registrar,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainMonitor = `-- name: UpdateDomainMonitor :one
UPDATE domain_monitors
SET name = $3, domain = $4, alerts_enabled = $5, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type UpdateDomainMonitorParams struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	Name          string    `json:"name"`
	Domain        string    `json:"domain"`
	AlertsEnabled bool      `json:"alerts_enabled"`
}

func (q *Queries) UpdateDomainMonitor(ctx context.Context, arg UpdateDomainMonitorParams) (DomainMonitor, error) {
	row := q.db.QueryRow(ctx, updateDomainMonitor,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Domain,
		arg.AlertsEnabled,
	)
	var i DomainMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Registrar,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainMonitorCheck = `-- name: UpdateDomainMonitorCheck :one
UPDATE domain_monitors
SET status          = $2,
    expires_at      = $3,
    registrar       = $4,
    error_msg       = $5,
    alerted_30d     = $6,
    alerted_14d     = $7,
    alerted_7d      = $8,
    last_checked_at = NOW(),
    next_check_at   = NOW() + INTERVAL '24 hours',
    updated_at      = NOW()
WHERE id = $1
RETURNING id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type UpdateDomainMonitorCheckParams struct {
	ID         uuid.UUID           `json:"id"`
	Status     DomainMonitorStatus `json:"status"`
	ExpiresAt  pgtype.Timestamptz  `json:"expires_at"`
	Registrar  pgtype.Text         `json:"registrar"`
	ErrorMsg   pgtype.Text         `json:"error_msg"`
	Alerted30d bool                `json:"alerted_30d"`
	Alerted14d bool                `json:"alerted_14d"`
	Alerted7d  bool                `json:"alerted_7d"`
}

func (q *Queries) UpdateDomainMonitorCheck(ctx context.Context, arg UpdateDomainMonitorCheckParams) (DomainMonitor, error) {
	row := q.db.QueryRow(ctx, updateDomainMonitorCheck,
		arg.ID,
		arg.Status,
		arg.ExpiresAt,
		arg.Registrar,
		arg.ErrorMsg,
		arg.Alerted30d,
		arg.Alerted14d,
		arg.Alerted7d,
	)
	var i DomainMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Registrar,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
