// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countResolvedStatusPageIncidentsForPage = `-- name: CountResolvedStatusPageIncidentsForPage :one
SELECT COUNT(DISTINCT spi.id)
FROM status_page_incidents spi
JOIN status_page_incident_monitors spim ON spim.incident_id = spi.id
JOIN status_page_monitors spm ON spm.monitor_type = spim.monitor_type AND spm.monitor_id = spim.monitor_id
WHERE spm.page_id = $1 AND spi.status = 'resolved'
`

func (q *Queries) CountResolvedStatusPageIncidentsForPage(ctx context.Context, pageID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countResolvedStatusPageIncidentsForPage, pageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStatusPageIncident = `-- name: CreateStatusPageIncident :one

INSERT INTO status_page_incidents (org_id, title, severity)
VALUES ($1, $2, $3)
RETURNING id, org_id, title, severity, status, created_at, updated_at, resolved_at
`

type CreateStatusPageIncidentParams struct {
	OrgID    uuid.UUID        `json:"org_id"`
	Title    string           `json:"title"`
	Severity IncidentSeverity `json:"severity"`
}

// ─── status_page_incidents ───────────────────────────────────────────────────
func (q *Queries) CreateStatusPageIncident(ctx context.Context, arg CreateStatusPageIncidentParams) (StatusPageIncident, error) {
	row := q.db.QueryRow(ctx, createStatusPageIncident, arg.OrgID, arg.Title, arg.Severity)
	var i StatusPageIncident
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const deleteStatusPageIncident = `-- name: DeleteStatusPageIncident :exec
DELETE FROM status_page_incidents WHERE id = $1 AND org_id = $2
`

type DeleteStatusPageIncidentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteStatusPageIncident(ctx context.Context, arg DeleteStatusPageIncidentParams) error {
	_, err := q.db.Exec(ctx, deleteStatusPageIncident, arg.ID, arg.OrgID)
	return err
}

const getLatestStatusPageIncidentUpdate = `-- name: GetLatestStatusPageIncidentUpdate :one
SELECT id, incident_id, message, status, created_at FROM status_page_incident_updates WHERE incident_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestStatusPageIncidentUpdate(ctx context.Context, incidentID uuid.UUID) (StatusPageIncidentUpdate, error) {
	row := q.db.QueryRow(ctx, getLatestStatusPageIncidentUpdate, incidentID)
	var i StatusPageIncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getStatusPageIncident = `-- name: GetStatusPageIncident :one
SELECT id, org_id, title, severity, status, created_at, updated_at, resolved_at FROM status_page_incidents WHERE id = $1 AND org_id = $2
`

type GetStatusPageIncidentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetStatusPageIncident(ctx context.Context, arg GetStatusPageIncidentParams) (StatusPageIncident, error) {
	row := q.db.QueryRow(ctx, getStatusPageIncident, arg.ID, arg.OrgID)
	var i StatusPageIncident
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertStatusPageIncidentMonitor = `-- name: InsertStatusPageIncidentMonitor :one

INSERT INTO status_page_incident_monitors (incident_id, monitor_type, monitor_id)
VALUES ($1, $2, $3)
RETURNING id, incident_id, monitor_type, monitor_id
`

type InsertStatusPageIncidentMonitorParams struct {
	IncidentID  uuid.UUID `json:"incident_id"`
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

// ─── status_page_incident_monitors ───────────────────────────────────────────
func (q *Queries) InsertStatusPageIncidentMonitor(ctx context.Context, arg InsertStatusPageIncidentMonitorParams) (StatusPageIncidentMonitor, error) {
	row := q.db.QueryRow(ctx, insertStatusPageIncidentMonitor, arg.IncidentID, arg.MonitorType, arg.MonitorID)
	var i StatusPageIncidentMonitor
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.MonitorType,
		&i.MonitorID,
	)
	return i, err
}

const insertStatusPageIncidentUpdate = `-- name: InsertStatusPageIncidentUpdate :one

INSERT INTO status_page_incident_updates (incident_id, message, status)
VALUES ($1, $2, $3)
RETURNING id, incident_id, message, status, created_at
`

type InsertStatusPageIncidentUpdateParams struct {
	IncidentID uuid.UUID      `json:"incident_id"`
	Message    string         `json:"message"`
	Status     IncidentStatus `json:"status"`
}

// ─── status_page_incident_updates ────────────────────────────────────────────
func (q *Queries) InsertStatusPageIncidentUpdate(ctx context.Context, arg InsertStatusPageIncidentUpdateParams) (StatusPageIncidentUpdate, error) {
	row := q.db.QueryRow(ctx, insertStatusPageIncidentUpdate, arg.IncidentID, arg.Message, arg.Status)
	var i StatusPageIncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveStatusPageIncidentsForPage = `-- name: ListActiveStatusPageIncidentsForPage :many

SELECT DISTINCT spi.id, spi.title, spi.severity, spi.status, spi.created_at
FROM status_page_incidents spi
JOIN status_page_incident_monitors spim ON spim.incident_id = spi.id
JOIN status_page_monitors spm ON spm.monitor_type = spim.monitor_type AND spm.monitor_id = spim.monitor_id
WHERE spm.page_id = $1 AND spi.status != 'resolved'
ORDER BY spi.created_at DESC
`

type ListActiveStatusPageIncidentsForPageRow struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	Severity  IncidentSeverity   `json:"severity"`
	Status    IncidentStatus     `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ─── public status page lookups (scoped by page_id) ──────────────────────────
func (q *Queries) ListActiveStatusPageIncidentsForPage(ctx context.Context, pageID uuid.UUID) ([]ListActiveStatusPageIncidentsForPageRow, error) {
	rows, err := q.db.Query(ctx, listActiveStatusPageIncidentsForPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveStatusPageIncidentsForPageRow{}
	for rows.Next() {
		var i ListActiveStatusPageIncidentsForPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedStatusPageIncidentsForPage = `-- name: ListResolvedStatusPageIncidentsForPage :many
SELECT DISTINCT spi.id, spi.title, spi.severity, spi.status, spi.created_at, spi.resolved_at
FROM status_page_incidents spi
JOIN status_page_incident_monitors spim ON spim.incident_id = spi.id
JOIN status_page_monitors spm ON spm.monitor_type = spim.monitor_type AND spm.monitor_id = spim.monitor_id
WHERE spm.page_id = $1 AND spi.status = 'resolved'
ORDER BY spi.resolved_at DESC
LIMIT $2 OFFSET $3
`

type ListResolvedStatusPageIncidentsForPageParams struct {
	PageID uuid.UUID `json:"page_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListResolvedStatusPageIncidentsForPageRow struct {
	ID         uuid.UUID          `json:"id"`
	Title      string             `json:"title"`
	Severity   IncidentSeverity   `json:"severity"`
	Status     IncidentStatus     `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) ListResolvedStatusPageIncidentsForPage(ctx context.Context, arg ListResolvedStatusPageIncidentsForPageParams) ([]ListResolvedStatusPageIncidentsForPageRow, error) {
	rows, err := q.db.Query(ctx, listResolvedStatusPageIncidentsForPage, arg.PageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResolvedStatusPageIncidentsForPageRow{}
	for rows.Next() {
		var i ListResolvedStatusPageIncidentsForPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageIncidentMonitors = `-- name: ListStatusPageIncidentMonitors :many
SELECT id, incident_id, monitor_type, monitor_id FROM status_page_incident_monitors WHERE incident_id = $1
`

func (q *Queries) ListStatusPageIncidentMonitors(ctx context.Context, incidentID uuid.UUID) ([]StatusPageIncidentMonitor, error) {
	rows, err := q.db.Query(ctx, listStatusPageIncidentMonitors, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageIncidentMonitor{}
	for rows.Next() {
		var i StatusPageIncidentMonitor
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.MonitorType,
			&i.MonitorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageIncidentUpdates = `-- name: ListStatusPageIncidentUpdates :many
SELECT id, incident_id, message, status, created_at FROM status_page_incident_updates WHERE incident_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStatusPageIncidentUpdates(ctx context.Context, incidentID uuid.UUID) ([]StatusPageIncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listStatusPageIncidentUpdates, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageIncidentUpdate{}
	for rows.Next() {
		var i StatusPageIncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPageIncidents = `-- name: ListStatusPageIncidents :many
SELECT spi.id, spi.org_id, spi.title, spi.severity, spi.status, spi.created_at, spi.updated_at, spi.resolved_at, COUNT(spim.id) AS monitor_count
FROM status_page_incidents spi
LEFT JOIN status_page_incident_monitors spim ON spim.incident_id = spi.id
WHERE spi.org_id = $1
GROUP BY spi.id
ORDER BY spi.created_at DESC
`

type ListStatusPageIncidentsRow struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Title        string             `json:"title"`
	Severity     IncidentSeverity   `json:"severity"`
	Status       IncidentStatus     `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	MonitorCount int64              `json:"monitor_count"`
}

func (q *Queries) ListStatusPageIncidents(ctx context.Context, orgID uuid.UUID) ([]ListStatusPageIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listStatusPageIncidents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStatusPageIncidentsRow{}
	for rows.Next() {
		var i ListStatusPageIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.MonitorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatusPageIncidentStatus = `-- name: UpdateStatusPageIncidentStatus :one
UPDATE status_page_incidents
SET status = $3,
    resolved_at = CASE WHEN $3 = 'resolved'::incident_status THEN NOW() ELSE resolved_at END,
    updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, title, severity, status, created_at, updated_at, resolved_at
`

type UpdateStatusPageIncidentStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	OrgID  uuid.UUID      `json:"org_id"`
	Status IncidentStatus `json:"status"`
}

func (q *Queries) UpdateStatusPageIncidentStatus(ctx context.Context, arg UpdateStatusPageIncidentStatusParams) (StatusPageIncident, error) {
	row := q.db.QueryRow(ctx, updateStatusPageIncidentStatus, arg.ID, arg.OrgID, arg.Status)
	var i StatusPageIncident
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const updateStatusPageIncidentTitle = `-- name: UpdateStatusPageIncidentTitle :one
UPDATE status_page_incidents
SET title = $3, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, title, severity, status, created_at, updated_at, resolved_at
`

type UpdateStatusPageIncidentTitleParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
	Title string    `json:"title"`
}

func (q *Queries) UpdateStatusPageIncidentTitle(ctx context.Context, arg UpdateStatusPageIncidentTitleParams) (StatusPageIncident, error) {
	row := q.db.QueryRow(ctx, updateStatusPageIncidentTitle, arg.ID, arg.OrgID, arg.Title)
	var i StatusPageIncident
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const updateStatusPageIncidentUpdateMessage = `-- name: UpdateStatusPageIncidentUpdateMessage :one
UPDATE status_page_incident_updates
SET message = $3
WHERE id = $1 AND incident_id = $2
RETURNING id, incident_id, message, status, created_at
`

type UpdateStatusPageIncidentUpdateMessageParams struct {
	ID         uuid.UUID `json:"id"`
	IncidentID uuid.UUID `json:"incident_id"`
	Message    string    `json:"message"`
}

func (q *Queries) UpdateStatusPageIncidentUpdateMessage(ctx context.Context, arg UpdateStatusPageIncidentUpdateMessageParams) (StatusPageIncidentUpdate, error) {
	row := q.db.QueryRow(ctx, updateStatusPageIncidentUpdateMessage, arg.ID, arg.IncidentID, arg.Message)
	var i StatusPageIncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
