// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMaintenanceWindows = `-- name: CountMaintenanceWindows :one
SELECT COUNT(*) FROM maintenance_windows WHERE org_id = $1
`

func (q *Queries) CountMaintenanceWindows(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMaintenanceWindows, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenanceWindow = `-- name: CreateMaintenanceWindow :one

INSERT INTO maintenance_windows (org_id, title, message, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, title, message, starts_at, ends_at, created_at, updated_at
`

type CreateMaintenanceWindowParams struct {
	OrgID    uuid.UUID          `json:"org_id"`
	Title    string             `json:"title"`
	Message  string             `json:"message"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

// ─── maintenance_windows ─────────────────────────────────────────────────────
func (q *Queries) CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceWindow,
		arg.OrgID,
		arg.Title,
		arg.Message,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Message,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMaintenanceWindow = `-- name: DeleteMaintenanceWindow :exec
DELETE FROM maintenance_windows WHERE id = $1 AND org_id = $2
`

type DeleteMaintenanceWindowParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteMaintenanceWindow(ctx context.Context, arg DeleteMaintenanceWindowParams) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceWindow, arg.ID, arg.OrgID)
	return err
}

const deleteMaintenanceWindowMonitors = `-- name: DeleteMaintenanceWindowMonitors :exec
DELETE FROM maintenance_window_monitors WHERE window_id = $1
`

func (q *Queries) DeleteMaintenanceWindowMonitors(ctx context.Context, windowID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceWindowMonitors, windowID)
	return err
}

const endMaintenanceWindowNow = `-- name: EndMaintenanceWindowNow :one
UPDATE maintenance_windows
SET ends_at = NOW(), updated_at = NOW()
WHERE id = $1 AND org_id = $2 AND (ends_at IS NULL OR ends_at > NOW())
RETURNING id, org_id, title, message, starts_at, ends_at, created_at, updated_at
`

type EndMaintenanceWindowNowParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) EndMaintenanceWindowNow(ctx context.Context, arg EndMaintenanceWindowNowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, endMaintenanceWindowNow, arg.ID, arg.OrgID)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Message,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveMaintenanceForOrg = `-- name: GetActiveMaintenanceForOrg :many

SELECT mw.id AS window_id, mw.title, mw.message, mwm.monitor_type, mwm.monitor_id
FROM maintenance_windows mw
JOIN maintenance_window_monitors mwm ON mwm.window_id = mw.id
WHERE mw.org_id = $1
  AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
`

type GetActiveMaintenanceForOrgRow struct {
	WindowID    uuid.UUID `json:"window_id"`
	Title       string    `json:"title"`
	Message     string    `json:"message"`
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

// ─── public status page lookups ──────────────────────────────────────────────
func (q *Queries) GetActiveMaintenanceForOrg(ctx context.Context, orgID uuid.UUID) ([]GetActiveMaintenanceForOrgRow, error) {
	rows, err := q.db.Query(ctx, getActiveMaintenanceForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveMaintenanceForOrgRow{}
	for rows.Next() {
		var i GetActiveMaintenanceForOrgRow
		if err := rows.Scan(
			&i.WindowID,
			&i.Title,
			&i.Message,
			&i.MonitorType,
			&i.MonitorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaintenanceWindow = `-- name: GetMaintenanceWindow :one
SELECT id, org_id, title, message, starts_at, ends_at, created_at, updated_at FROM maintenance_windows WHERE id = $1 AND org_id = $2
`

type GetMaintenanceWindowParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetMaintenanceWindow(ctx context.Context, arg GetMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceWindow, arg.ID, arg.OrgID)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Message,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMaintenanceWindowMonitor = `-- name: InsertMaintenanceWindowMonitor :one
INSERT INTO maintenance_window_monitors (window_id, monitor_type, monitor_id)
VALUES ($1, $2, $3)
RETURNING id, window_id, monitor_type, monitor_id
`

type InsertMaintenanceWindowMonitorParams struct {
	WindowID    uuid.UUID `json:"window_id"`
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

func (q *Queries) InsertMaintenanceWindowMonitor(ctx context.Context, arg InsertMaintenanceWindowMonitorParams) (MaintenanceWindowMonitor, error) {
	row := q.db.QueryRow(ctx, insertMaintenanceWindowMonitor, arg.WindowID, arg.MonitorType, arg.MonitorID)
	var i MaintenanceWindowMonitor
	err := row.Scan(
		&i.ID,
		&i.WindowID,
		&i.MonitorType,
		&i.MonitorID,
	)
	return i, err
}

const listMaintenanceWindowMonitors = `-- name: ListMaintenanceWindowMonitors :many

SELECT id, window_id, monitor_type, monitor_id FROM maintenance_window_monitors WHERE window_id = $1
`

// ─── maintenance_window_monitors ─────────────────────────────────────────────
func (q *Queries) ListMaintenanceWindowMonitors(ctx context.Context, windowID uuid.UUID) ([]MaintenanceWindowMonitor, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindowMonitors, windowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindowMonitor{}
	for rows.Next() {
		var i MaintenanceWindowMonitor
		if err := rows.Scan(
			&i.ID,
			&i.WindowID,
			&i.MonitorType,
			&i.MonitorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindows = `-- name: ListMaintenanceWindows :many
SELECT mw.id, mw.org_id, mw.title, mw.message, mw.starts_at, mw.ends_at, mw.created_at, mw.updated_at, COUNT(mwm.id) AS monitor_count
FROM maintenance_windows mw
LEFT JOIN maintenance_window_monitors mwm ON mwm.window_id = mw.id
WHERE mw.org_id = $1
GROUP BY mw.id
ORDER BY mw.starts_at DESC
LIMIT 200
`

type ListMaintenanceWindowsRow struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Title        string             `json:"title"`
	Message      string             `json:"message"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	MonitorCount int64              `json:"monitor_count"`
}

func (q *Queries) ListMaintenanceWindows(ctx context.Context, orgID uuid.UUID) ([]ListMaintenanceWindowsRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindows, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceWindowsRow{}
	for rows.Next() {
		var i ListMaintenanceWindowsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Title,
			&i.Message,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MonitorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenanceWindow = `-- name: UpdateMaintenanceWindow :one
UPDATE maintenance_windows
SET title = $3, message = $4, starts_at = $5, ends_at = $6, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, title, message, starts_at, ends_at, created_at, updated_at
`

type UpdateMaintenanceWindowParams struct {
	ID       uuid.UUID          `json:"id"`
	OrgID    uuid.UUID          `json:"org_id"`
	Title    string             `json:"title"`
	Message  string             `json:"message"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) UpdateMaintenanceWindow(ctx context.Context, arg UpdateMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceWindow,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Message,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Title,
		&i.Message,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
