// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DnsRecordType string

const (
	DnsRecordTypeA     DnsRecordType = "A"
	DnsRecordTypeAAAA  DnsRecordType = "AAAA"
	DnsRecordTypeCNAME DnsRecordType = "CNAME"
	DnsRecordTypeMX    DnsRecordType = "MX"
	DnsRecordTypeTXT   DnsRecordType = "TXT"
	DnsRecordTypeNS    DnsRecordType = "NS"
)

func (e *DnsRecordType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DnsRecordType(s)
	case string:
		*e = DnsRecordType(s)
	default:
		return fmt.Errorf("unsupported scan type for DnsRecordType: %T", src)
	}
	return nil
}

type NullDnsRecordType struct {
	DnsRecordType DnsRecordType `json:"dns_record_type"`
	Valid         bool          `json:"valid"` // Valid is true if DnsRecordType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDnsRecordType) Scan(value interface{}) error {
	if value == nil {
		ns.DnsRecordType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DnsRecordType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDnsRecordType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DnsRecordType), nil
}

type DomainMonitorStatus string

const (
	DomainMonitorStatusWaiting      DomainMonitorStatus = "waiting"
	DomainMonitorStatusUp           DomainMonitorStatus = "up"
	DomainMonitorStatusExpiringSoon DomainMonitorStatus = "expiring_soon"
	DomainMonitorStatusExpired      DomainMonitorStatus = "expired"
	DomainMonitorStatusError        DomainMonitorStatus = "error"
	DomainMonitorStatusPaused       DomainMonitorStatus = "paused"
)

func (e *DomainMonitorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DomainMonitorStatus(s)
	case string:
		*e = DomainMonitorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DomainMonitorStatus: %T", src)
	}
	return nil
}

type NullDomainMonitorStatus struct {
	DomainMonitorStatus DomainMonitorStatus `json:"domain_monitor_status"`
	Valid               bool                `json:"valid"` // Valid is true if DomainMonitorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDomainMonitorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DomainMonitorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DomainMonitorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDomainMonitorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DomainMonitorStatus), nil
}

type HttpMethod string

const (
	HttpMethodGET  HttpMethod = "GET"
	HttpMethodHEAD HttpMethod = "HEAD"
	HttpMethodPOST HttpMethod = "POST"
)

func (e *HttpMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HttpMethod(s)
	case string:
		*e = HttpMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for HttpMethod: %T", src)
	}
	return nil
}

type NullHttpMethod struct {
	HttpMethod HttpMethod `json:"http_method"`
	Valid      bool       `json:"valid"` // Valid is true if HttpMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHttpMethod) Scan(value interface{}) error {
	if value == nil {
		ns.HttpMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HttpMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHttpMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HttpMethod), nil
}

type IncidentSeverity string

const (
	IncidentSeverityMinor    IncidentSeverity = "minor"
	IncidentSeverityMajor    IncidentSeverity = "major"
	IncidentSeverityCritical IncidentSeverity = "critical"
)

func (e *IncidentSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentSeverity(s)
	case string:
		*e = IncidentSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentSeverity: %T", src)
	}
	return nil
}

type NullIncidentSeverity struct {
	IncidentSeverity IncidentSeverity `json:"incident_severity"`
	Valid            bool             `json:"valid"` // Valid is true if IncidentSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentSeverity), nil
}

type IncidentStatus string

const (
	IncidentStatusInvestigating IncidentStatus = "investigating"
	IncidentStatusIdentified    IncidentStatus = "identified"
	IncidentStatusMonitoring    IncidentStatus = "monitoring"
	IncidentStatusResolved      IncidentStatus = "resolved"
)

func (e *IncidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentStatus(s)
	case string:
		*e = IncidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentStatus: %T", src)
	}
	return nil
}

type NullIncidentStatus struct {
	IncidentStatus IncidentStatus `json:"incident_status"`
	Valid          bool           `json:"valid"` // Valid is true if IncidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentStatus), nil
}

type KeywordMode string

const (
	KeywordModeContains    KeywordMode = "contains"
	KeywordModeNotContains KeywordMode = "not_contains"
)

func (e *KeywordMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KeywordMode(s)
	case string:
		*e = KeywordMode(s)
	default:
		return fmt.Errorf("unsupported scan type for KeywordMode: %T", src)
	}
	return nil
}

type NullKeywordMode struct {
	KeywordMode KeywordMode `json:"keyword_mode"`
	Valid       bool        `json:"valid"` // Valid is true if KeywordMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKeywordMode) Scan(value interface{}) error {
	if value == nil {
		ns.KeywordMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KeywordMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKeywordMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KeywordMode), nil
}

type MonitorStatus string

const (
	MonitorStatusWaiting MonitorStatus = "waiting"
	MonitorStatusUp      MonitorStatus = "up"
	MonitorStatusDown    MonitorStatus = "down"
	MonitorStatusPaused  MonitorStatus = "paused"
)

func (e *MonitorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorStatus(s)
	case string:
		*e = MonitorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorStatus: %T", src)
	}
	return nil
}

type NullMonitorStatus struct {
	MonitorStatus MonitorStatus `json:"monitor_status"`
	Valid         bool          `json:"valid"` // Valid is true if MonitorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorStatus), nil
}

type NotificationChannelType string

const (
	NotificationChannelTypeTelegram NotificationChannelType = "telegram"
	NotificationChannelTypeEmail    NotificationChannelType = "email"
	NotificationChannelTypeWebhook  NotificationChannelType = "webhook"
	NotificationChannelTypeSlack    NotificationChannelType = "slack"
	NotificationChannelTypeSms      NotificationChannelType = "sms"
)

func (e *NotificationChannelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannelType(s)
	case string:
		*e = NotificationChannelType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannelType: %T", src)
	}
	return nil
}

type NullNotificationChannelType struct {
	NotificationChannelType NotificationChannelType `json:"notification_channel_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if NotificationChannelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannelType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannelType), nil
}

type Plan string

const (
	PlanHobby      Plan = "hobby"
	PlanSolo       Plan = "solo"
	PlanStartup    Plan = "startup"
	PlanEnterprise Plan = "enterprise"
)

func (e *Plan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Plan(s)
	case string:
		*e = Plan(s)
	default:
		return fmt.Errorf("unsupported scan type for Plan: %T", src)
	}
	return nil
}

type NullPlan struct {
	Plan  Plan `json:"plan"`
	Valid bool `json:"valid"` // Valid is true if Plan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlan) Scan(value interface{}) error {
	if value == nil {
		ns.Plan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Plan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Plan), nil
}

type PortExpectedState string

const (
	PortExpectedStateOpen   PortExpectedState = "open"
	PortExpectedStateClosed PortExpectedState = "closed"
)

func (e *PortExpectedState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PortExpectedState(s)
	case string:
		*e = PortExpectedState(s)
	default:
		return fmt.Errorf("unsupported scan type for PortExpectedState: %T", src)
	}
	return nil
}

type NullPortExpectedState struct {
	PortExpectedState PortExpectedState `json:"port_expected_state"`
	Valid             bool              `json:"valid"` // Valid is true if PortExpectedState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPortExpectedState) Scan(value interface{}) error {
	if value == nil {
		ns.PortExpectedState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PortExpectedState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPortExpectedState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PortExpectedState), nil
}

type SslMonitorStatus string

const (
	SslMonitorStatusWaiting      SslMonitorStatus = "waiting"
	SslMonitorStatusUp           SslMonitorStatus = "up"
	SslMonitorStatusExpiringSoon SslMonitorStatus = "expiring_soon"
	SslMonitorStatusExpired      SslMonitorStatus = "expired"
	SslMonitorStatusError        SslMonitorStatus = "error"
	SslMonitorStatusPaused       SslMonitorStatus = "paused"
)

func (e *SslMonitorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SslMonitorStatus(s)
	case string:
		*e = SslMonitorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SslMonitorStatus: %T", src)
	}
	return nil
}

type NullSslMonitorStatus struct {
	SslMonitorStatus SslMonitorStatus `json:"ssl_monitor_status"`
	Valid            bool             `json:"valid"` // Valid is true if SslMonitorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSslMonitorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SslMonitorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SslMonitorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSslMonitorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SslMonitorStatus), nil
}

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Label      string             `json:"label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type CronIncident struct {
	ID         uuid.UUID          `json:"id"`
	MonitorID  uuid.UUID          `json:"monitor_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	AlertCount int32              `json:"alert_count"`
}

type CronMonitor struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	Name                 string             `json:"name"`
	Schedule             string             `json:"schedule"`
	GracePeriodMins      int32              `json:"grace_period_mins"`
	PingToken            string             `json:"ping_token"`
	Status               MonitorStatus      `json:"status"`
	AlertsEnabled        bool               `json:"alerts_enabled"`
	LastPingAt           pgtype.Timestamptz `json:"last_ping_at"`
	NextPingAt           pgtype.Timestamptz `json:"next_ping_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	MaxAlertsPerIncident int32              `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32              `json:"alert_after_n_failures"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
}

type CronPing struct {
	ID         uuid.UUID          `json:"id"`
	MonitorID  uuid.UUID          `json:"monitor_id"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	SourceIp   string             `json:"source_ip"`
	Metadata   []byte             `json:"metadata"`
}

type DnsCheck struct {
	ID             uuid.UUID          `json:"id"`
	MonitorID      uuid.UUID          `json:"monitor_id"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
	ResponseTimeMs int32              `json:"response_time_ms"`
	IsUp           bool               `json:"is_up"`
	ResolvedValue  pgtype.Text        `json:"resolved_value"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
}

type DnsIncident struct {
	ID         uuid.UUID          `json:"id"`
	MonitorID  uuid.UUID          `json:"monitor_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	AlertCount int32              `json:"alert_count"`
}

type DnsMonitor struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	Name                 string             `json:"name"`
	Hostname             string             `json:"hostname"`
	RecordType           DnsRecordType      `json:"record_type"`
	ExpectedValue        pgtype.Text        `json:"expected_value"`
	BaselineCaptured     bool               `json:"baseline_captured"`
	LastResolvedValue    pgtype.Text        `json:"last_resolved_value"`
	IntervalMins         int32              `json:"interval_mins"`
	Status               MonitorStatus      `json:"status"`
	AlertsEnabled        bool               `json:"alerts_enabled"`
	MaxAlertsPerIncident int32              `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32              `json:"alert_after_n_failures"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
	LastCheckedAt        pgtype.Timestamptz `json:"last_checked_at"`
	NextCheckAt          pgtype.Timestamptz `json:"next_check_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type DomainMonitor struct {
	ID                   uuid.UUID           `json:"id"`
	OrgID                uuid.UUID           `json:"org_id"`
	Name                 string              `json:"name"`
	Domain               string              `json:"domain"`
	Status               DomainMonitorStatus `json:"status"`
	AlertsEnabled        bool                `json:"alerts_enabled"`
	ExpiresAt            pgtype.Timestamptz  `json:"expires_at"`
	Registrar            pgtype.Text         `json:"registrar"`
	ErrorMsg             pgtype.Text         `json:"error_msg"`
	Alerted30d           bool                `json:"alerted_30d"`
	Alerted14d           bool                `json:"alerted_14d"`
	Alerted7d            bool                `json:"alerted_7d"`
	LastCheckedAt        pgtype.Timestamptz  `json:"last_checked_at"`
	NextCheckAt          pgtype.Timestamptz  `json:"next_check_at"`
	CreatedAt            pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz  `json:"updated_at"`
	AlertAfterNFailures  int32               `json:"alert_after_n_failures"`
	ConsecutiveFailures  int32               `json:"consecutive_failures"`
	MaxAlertsPerIncident int32               `json:"max_alerts_per_incident"`
	AlertCount           int32               `json:"alert_count"`
}

type FeatureSuggestion struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MaintenanceWindow struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	Title     string             `json:"title"`
	Message   string             `json:"message"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MaintenanceWindowMonitor struct {
	ID          uuid.UUID `json:"id"`
	WindowID    uuid.UUID `json:"window_id"`
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

type MonitorNotificationChannel struct {
	ID          uuid.UUID `json:"id"`
	ChannelID   uuid.UUID `json:"channel_id"`
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

type NotificationChannel struct {
	ID                 uuid.UUID               `json:"id"`
	OrgID              uuid.UUID               `json:"org_id"`
	Type               NotificationChannelType `json:"type"`
	Name               string                  `json:"name"`
	Config             []byte                  `json:"config"`
	Enabled            bool                    `json:"enabled"`
	CreatedAt          pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz      `json:"updated_at"`
	LastDeliveryStatus pgtype.Text             `json:"last_delivery_status"`
	LastDeliveryDetail pgtype.Text             `json:"last_delivery_detail"`
	LastDeliveryAt     pgtype.Timestamptz      `json:"last_delivery_at"`
}

type Org struct {
	ID                      uuid.UUID          `json:"id"`
	Name                    string             `json:"name"`
	Plan                    Plan               `json:"plan"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	TelegramChatID          pgtype.Text        `json:"telegram_chat_id"`
	SubscriptionStatus      string             `json:"subscription_status"`
	PlanRenewsAt            pgtype.Timestamptz `json:"plan_renews_at"`
	BillingCycle            string             `json:"billing_cycle"`
	AlertEmail              pgtype.Text        `json:"alert_email"`
	EmailAlertsEnabled      bool               `json:"email_alerts_enabled"`
	PaddleCustomerID        pgtype.Text        `json:"paddle_customer_id"`
	PaddleSubscriptionID    pgtype.Text        `json:"paddle_subscription_id"`
	SmsCreditsUsedThisMonth int32              `json:"sms_credits_used_this_month"`
	SmsCreditsResetAt       pgtype.Date        `json:"sms_credits_reset_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PortCheck struct {
	ID             uuid.UUID          `json:"id"`
	MonitorID      uuid.UUID          `json:"monitor_id"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
	ResponseTimeMs int32              `json:"response_time_ms"`
	IsUp           bool               `json:"is_up"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
}

type PortIncident struct {
	ID         uuid.UUID          `json:"id"`
	MonitorID  uuid.UUID          `json:"monitor_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	AlertCount int32              `json:"alert_count"`
}

type PortMonitor struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	Name                 string             `json:"name"`
	Host                 string             `json:"host"`
	Port                 int32              `json:"port"`
	ExpectedState        PortExpectedState  `json:"expected_state"`
	IntervalMins         int32              `json:"interval_mins"`
	Status               MonitorStatus      `json:"status"`
	AlertsEnabled        bool               `json:"alerts_enabled"`
	MaxAlertsPerIncident int32              `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32              `json:"alert_after_n_failures"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
	LastCheckedAt        pgtype.Timestamptz `json:"last_checked_at"`
	NextCheckAt          pgtype.Timestamptz `json:"next_check_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SslMonitor struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	Name                 string             `json:"name"`
	Hostname             string             `json:"hostname"`
	Status               SslMonitorStatus   `json:"status"`
	AlertsEnabled        bool               `json:"alerts_enabled"`
	ExpiresAt            pgtype.Timestamptz `json:"expires_at"`
	Issuer               pgtype.Text        `json:"issuer"`
	ErrorMsg             pgtype.Text        `json:"error_msg"`
	Alerted30d           bool               `json:"alerted_30d"`
	Alerted14d           bool               `json:"alerted_14d"`
	Alerted7d            bool               `json:"alerted_7d"`
	LastCheckedAt        pgtype.Timestamptz `json:"last_checked_at"`
	NextCheckAt          pgtype.Timestamptz `json:"next_check_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	AlertAfterNFailures  int32              `json:"alert_after_n_failures"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
	MaxAlertsPerIncident int32              `json:"max_alerts_per_incident"`
	AlertCount           int32              `json:"alert_count"`
}

type StatusPage struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	LogoUrl      string             `json:"logo_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	HideBranding bool               `json:"hide_branding"`
	Layout       string             `json:"layout"`
}

type StatusPageIncident struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	Title      string             `json:"title"`
	Severity   IncidentSeverity   `json:"severity"`
	Status     IncidentStatus     `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type StatusPageIncidentMonitor struct {
	ID          uuid.UUID `json:"id"`
	IncidentID  uuid.UUID `json:"incident_id"`
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

type StatusPageIncidentUpdate struct {
	ID         uuid.UUID          `json:"id"`
	IncidentID uuid.UUID          `json:"incident_id"`
	Message    string             `json:"message"`
	Status     IncidentStatus     `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type StatusPageMonitor struct {
	ID           uuid.UUID `json:"id"`
	PageID       uuid.UUID `json:"page_id"`
	MonitorType  string    `json:"monitor_type"`
	MonitorID    uuid.UUID `json:"monitor_id"`
	DisplayName  string    `json:"display_name"`
	DisplayOrder int32     `json:"display_order"`
}

type UptimeCheck struct {
	ID             uuid.UUID          `json:"id"`
	MonitorID      uuid.UUID          `json:"monitor_id"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
	StatusCode     pgtype.Int4        `json:"status_code"`
	ResponseTimeMs int32              `json:"response_time_ms"`
	IsUp           bool               `json:"is_up"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
}

type UptimeIncident struct {
	ID         uuid.UUID          `json:"id"`
	MonitorID  uuid.UUID          `json:"monitor_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	AlertCount int32              `json:"alert_count"`
}

type UptimeMonitor struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	Name                 string             `json:"name"`
	Url                  string             `json:"url"`
	IntervalMins         int32              `json:"interval_mins"`
	Status               MonitorStatus      `json:"status"`
	AlertsEnabled        bool               `json:"alerts_enabled"`
	MaxAlertsPerIncident int32              `json:"max_alerts_per_incident"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
	LastCheckedAt        pgtype.Timestamptz `json:"last_checked_at"`
	NextCheckAt          pgtype.Timestamptz `json:"next_check_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	Keyword              pgtype.Text        `json:"keyword"`
	KeywordMode          KeywordMode        `json:"keyword_mode"`
	KeywordCaseSensitive bool               `json:"keyword_case_sensitive"`
	JsonAssertions       []byte             `json:"json_assertions"`
	MaxResponseTimeMs    int32              `json:"max_response_time_ms"`
	AlertAfterNFailures  int32              `json:"alert_after_n_failures"`
	HttpMethod           HttpMethod         `json:"http_method"`
	AcceptedStatusCodes  []int32            `json:"accepted_status_codes"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	OrgID           uuid.UUID          `json:"org_id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TermsVersion    pgtype.Text        `json:"terms_version"`
	TermsAcceptedAt pgtype.Timestamptz `json:"terms_accepted_at"`
}
