// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Plan string

const (
	PlanHobbyist Plan = "hobbyist"
	PlanIndie    Plan = "indie"
	PlanStudio   Plan = "studio"
	PlanAgency   Plan = "agency"
)

func (e *Plan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Plan(s)
	case string:
		*e = Plan(s)
	default:
		return fmt.Errorf("unsupported scan type for Plan: %T", src)
	}
	return nil
}

type NullPlan struct {
	Plan  Plan `json:"plan"`
	Valid bool `json:"valid"` // Valid is true if Plan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlan) Scan(value interface{}) error {
	if value == nil {
		ns.Plan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Plan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Plan), nil
}

type Org struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Plan      Plan               `json:"plan"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
