// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MonitorStatus string

const (
	MonitorStatusWaiting MonitorStatus = "waiting"
	MonitorStatusUp      MonitorStatus = "up"
	MonitorStatusDown    MonitorStatus = "down"
	MonitorStatusPaused  MonitorStatus = "paused"
)

func (e *MonitorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorStatus(s)
	case string:
		*e = MonitorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorStatus: %T", src)
	}
	return nil
}

type NullMonitorStatus struct {
	MonitorStatus MonitorStatus `json:"monitor_status"`
	Valid         bool          `json:"valid"` // Valid is true if MonitorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorStatus), nil
}

type Plan string

const (
	PlanHobbyist Plan = "hobbyist"
	PlanIndie    Plan = "indie"
	PlanStudio   Plan = "studio"
	PlanAgency   Plan = "agency"
)

func (e *Plan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Plan(s)
	case string:
		*e = Plan(s)
	default:
		return fmt.Errorf("unsupported scan type for Plan: %T", src)
	}
	return nil
}

type NullPlan struct {
	Plan  Plan `json:"plan"`
	Valid bool `json:"valid"` // Valid is true if Plan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlan) Scan(value interface{}) error {
	if value == nil {
		ns.Plan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Plan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Plan), nil
}

type CronIncident struct {
	ID         uuid.UUID          `json:"id"`
	MonitorID  uuid.UUID          `json:"monitor_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	AlertCount int32              `json:"alert_count"`
}

type CronMonitor struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	Name                 string             `json:"name"`
	Schedule             string             `json:"schedule"`
	GracePeriodMins      int32              `json:"grace_period_mins"`
	PingToken            string             `json:"ping_token"`
	Status               MonitorStatus      `json:"status"`
	AlertsEnabled        bool               `json:"alerts_enabled"`
	LastPingAt           pgtype.Timestamptz `json:"last_ping_at"`
	NextPingAt           pgtype.Timestamptz `json:"next_ping_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	MaxAlertsPerIncident int32              `json:"max_alerts_per_incident"`
}

type CronPing struct {
	ID         uuid.UUID          `json:"id"`
	MonitorID  uuid.UUID          `json:"monitor_id"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	SourceIp   string             `json:"source_ip"`
}

type Org struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Plan           Plan               `json:"plan"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TelegramChatID pgtype.Text        `json:"telegram_chat_id"`
}

type PasswordResetToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UptimeCheck struct {
	ID             uuid.UUID          `json:"id"`
	MonitorID      uuid.UUID          `json:"monitor_id"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
	StatusCode     pgtype.Int4        `json:"status_code"`
	ResponseTimeMs int32              `json:"response_time_ms"`
	IsUp           bool               `json:"is_up"`
}

type UptimeIncident struct {
	ID         uuid.UUID          `json:"id"`
	MonitorID  uuid.UUID          `json:"monitor_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	AlertCount int32              `json:"alert_count"`
}

type UptimeMonitor struct {
	ID                   uuid.UUID          `json:"id"`
	OrgID                uuid.UUID          `json:"org_id"`
	Name                 string             `json:"name"`
	Url                  string             `json:"url"`
	IntervalMins         int32              `json:"interval_mins"`
	Status               MonitorStatus      `json:"status"`
	AlertsEnabled        bool               `json:"alerts_enabled"`
	MaxAlertsPerIncident int32              `json:"max_alerts_per_incident"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
	LastCheckedAt        pgtype.Timestamptz `json:"last_checked_at"`
	NextCheckAt          pgtype.Timestamptz `json:"next_check_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	OrgID        uuid.UUID          `json:"org_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
