// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCronPings = `-- name: CountCronPings :one
SELECT COUNT(*) FROM cron_pings WHERE monitor_id = $1
`

func (q *Queries) CountCronPings(ctx context.Context, monitorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCronPings, monitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCronIncident = `-- name: CreateCronIncident :one
INSERT INTO cron_incidents (monitor_id)
VALUES ($1)
RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) CreateCronIncident(ctx context.Context, monitorID uuid.UUID) (CronIncident, error) {
	row := q.db.QueryRow(ctx, createCronIncident, monitorID)
	var i CronIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const createCronMonitor = `-- name: CreateCronMonitor :one
INSERT INTO cron_monitors (org_id, name, schedule, grace_period_mins, ping_token, max_alerts_per_incident, alert_after_n_failures)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures
`

type CreateCronMonitorParams struct {
	OrgID                uuid.UUID `json:"org_id"`
	Name                 string    `json:"name"`
	Schedule             string    `json:"schedule"`
	GracePeriodMins      int32     `json:"grace_period_mins"`
	PingToken            string    `json:"ping_token"`
	MaxAlertsPerIncident int32     `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32     `json:"alert_after_n_failures"`
}

func (q *Queries) CreateCronMonitor(ctx context.Context, arg CreateCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, createCronMonitor,
		arg.OrgID,
		arg.Name,
		arg.Schedule,
		arg.GracePeriodMins,
		arg.PingToken,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
	)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const createCronPing = `-- name: CreateCronPing :one
INSERT INTO cron_pings (monitor_id, received_at, source_ip)
VALUES ($1, NOW(), $2)
RETURNING id, monitor_id, received_at, source_ip
`

type CreateCronPingParams struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	SourceIp  string    `json:"source_ip"`
}

func (q *Queries) CreateCronPing(ctx context.Context, arg CreateCronPingParams) (CronPing, error) {
	row := q.db.QueryRow(ctx, createCronPing, arg.MonitorID, arg.SourceIp)
	var i CronPing
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ReceivedAt,
		&i.SourceIp,
	)
	return i, err
}

const deleteCronMonitor = `-- name: DeleteCronMonitor :exec
DELETE FROM cron_monitors WHERE id = $1 AND org_id = $2
`

type DeleteCronMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteCronMonitor(ctx context.Context, arg DeleteCronMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteCronMonitor, arg.ID, arg.OrgID)
	return err
}

const deleteOldCronPings = `-- name: DeleteOldCronPings :exec
DELETE FROM cron_pings WHERE received_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldCronPings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldCronPings)
	return err
}

const getCronMonitor = `-- name: GetCronMonitor :one
SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures FROM cron_monitors WHERE id = $1 AND org_id = $2
`

type GetCronMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetCronMonitor(ctx context.Context, arg GetCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, getCronMonitor, arg.ID, arg.OrgID)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const getCronMonitorByToken = `-- name: GetCronMonitorByToken :one
SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures FROM cron_monitors WHERE ping_token = $1
`

func (q *Queries) GetCronMonitorByToken(ctx context.Context, pingToken string) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, getCronMonitorByToken, pingToken)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const incrementCronConsecutiveFailures = `-- name: IncrementCronConsecutiveFailures :one
UPDATE cron_monitors
SET consecutive_failures = consecutive_failures + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures
`

func (q *Queries) IncrementCronConsecutiveFailures(ctx context.Context, id uuid.UUID) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, incrementCronConsecutiveFailures, id)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const incrementCronIncidentAlertCount = `-- name: IncrementCronIncidentAlertCount :one
UPDATE cron_incidents SET alert_count = alert_count + 1 WHERE id = $1 RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) IncrementCronIncidentAlertCount(ctx context.Context, id uuid.UUID) (CronIncident, error) {
	row := q.db.QueryRow(ctx, incrementCronIncidentAlertCount, id)
	var i CronIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const listCronIncidents = `-- name: ListCronIncidents :many
SELECT id, monitor_id, started_at, resolved_at, alert_count FROM cron_incidents WHERE monitor_id = $1 ORDER BY started_at DESC
`

func (q *Queries) ListCronIncidents(ctx context.Context, monitorID uuid.UUID) ([]CronIncident, error) {
	rows, err := q.db.Query(ctx, listCronIncidents, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronIncident{}
	for rows.Next() {
		var i CronIncident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AlertCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronMonitors = `-- name: ListCronMonitors :many
SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures FROM cron_monitors WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCronMonitors(ctx context.Context, orgID uuid.UUID) ([]CronMonitor, error) {
	rows, err := q.db.Query(ctx, listCronMonitors, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronMonitor{}
	for rows.Next() {
		var i CronMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Schedule,
			&i.GracePeriodMins,
			&i.PingToken,
			&i.Status,
			&i.AlertsEnabled,
			&i.LastPingAt,
			&i.NextPingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxAlertsPerIncident,
			&i.AlertAfterNFailures,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronPings = `-- name: ListCronPings :many
SELECT id, monitor_id, received_at, source_ip FROM cron_pings WHERE monitor_id = $1 ORDER BY received_at DESC LIMIT $2 OFFSET $3
`

type ListCronPingsParams struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListCronPings(ctx context.Context, arg ListCronPingsParams) ([]CronPing, error) {
	rows, err := q.db.Query(ctx, listCronPings, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronPing{}
	for rows.Next() {
		var i CronPing
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ReceivedAt,
			&i.SourceIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueCronMonitors = `-- name: ListOverdueCronMonitors :many
SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures FROM cron_monitors
WHERE status = 'up' AND next_ping_at < NOW()
  AND NOT EXISTS (
    SELECT 1 FROM maintenance_window_monitors mwm
    JOIN maintenance_windows mw ON mw.id = mwm.window_id
    WHERE mwm.monitor_type = 'cron' AND mwm.monitor_id = cron_monitors.id
      AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
  )
`

func (q *Queries) ListOverdueCronMonitors(ctx context.Context) ([]CronMonitor, error) {
	rows, err := q.db.Query(ctx, listOverdueCronMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronMonitor{}
	for rows.Next() {
		var i CronMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Schedule,
			&i.GracePeriodMins,
			&i.PingToken,
			&i.Status,
			&i.AlertsEnabled,
			&i.LastPingAt,
			&i.NextPingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxAlertsPerIncident,
			&i.AlertAfterNFailures,
			&i.ConsecutiveFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseCronMonitor = `-- name: PauseCronMonitor :one
UPDATE cron_monitors SET status = 'paused', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures
`

type PauseCronMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) PauseCronMonitor(ctx context.Context, arg PauseCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, pauseCronMonitor, arg.ID, arg.OrgID)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const resolveLatestCronIncident = `-- name: ResolveLatestCronIncident :one
UPDATE cron_incidents
SET resolved_at = NOW()
WHERE id = (
    SELECT ci.id FROM cron_incidents ci
    WHERE ci.monitor_id = $1 AND ci.resolved_at IS NULL
    ORDER BY ci.started_at DESC
    LIMIT 1
)
RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) ResolveLatestCronIncident(ctx context.Context, monitorID uuid.UUID) (CronIncident, error) {
	row := q.db.QueryRow(ctx, resolveLatestCronIncident, monitorID)
	var i CronIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const resumeCronMonitor = `-- name: ResumeCronMonitor :one
UPDATE cron_monitors SET status = 'waiting', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures
`

type ResumeCronMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) ResumeCronMonitor(ctx context.Context, arg ResumeCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, resumeCronMonitor, arg.ID, arg.OrgID)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const updateCronMonitor = `-- name: UpdateCronMonitor :one
UPDATE cron_monitors
SET name = $3, schedule = $4, grace_period_mins = $5, alerts_enabled = $6, max_alerts_per_incident = $7,
    alert_after_n_failures = $8, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures
`

type UpdateCronMonitorParams struct {
	ID                   uuid.UUID `json:"id"`
	OrgID                uuid.UUID `json:"org_id"`
	Name                 string    `json:"name"`
	Schedule             string    `json:"schedule"`
	GracePeriodMins      int32     `json:"grace_period_mins"`
	AlertsEnabled        bool      `json:"alerts_enabled"`
	MaxAlertsPerIncident int32     `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32     `json:"alert_after_n_failures"`
}

func (q *Queries) UpdateCronMonitor(ctx context.Context, arg UpdateCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, updateCronMonitor,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Schedule,
		arg.GracePeriodMins,
		arg.AlertsEnabled,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
	)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const updateCronMonitorDown = `-- name: UpdateCronMonitorDown :exec
UPDATE cron_monitors
SET status = 'down', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateCronMonitorDown(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateCronMonitorDown, id)
	return err
}

const updateCronMonitorPing = `-- name: UpdateCronMonitorPing :one
UPDATE cron_monitors
SET status = 'up', last_ping_at = $3, next_ping_at = $4, consecutive_failures = 0, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures
`

type UpdateCronMonitorPingParams struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	LastPingAt pgtype.Timestamptz `json:"last_ping_at"`
	NextPingAt pgtype.Timestamptz `json:"next_ping_at"`
}

func (q *Queries) UpdateCronMonitorPing(ctx context.Context, arg UpdateCronMonitorPingParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, updateCronMonitorPing,
		arg.ID,
		arg.OrgID,
		arg.LastPingAt,
		arg.NextPingAt,
	)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
	)
	return i, err
}
