// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCronRun = `-- name: CompleteCronRun :one
UPDATE cron_runs
SET completed_at = NOW()
WHERE id = (
    SELECT cr.id FROM cron_runs cr
    WHERE cr.monitor_id = $1 AND cr.completed_at IS NULL
    ORDER BY cr.started_at DESC
    LIMIT 1
)
RETURNING id, monitor_id, started_at, completed_at, alerted_at, overlap
`

func (q *Queries) CompleteCronRun(ctx context.Context, monitorID uuid.UUID) (CronRun, error) {
	row := q.db.QueryRow(ctx, completeCronRun, monitorID)
	var i CronRun
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.AlertedAt,
		&i.Overlap,
	)
	return i, err
}

const countCronPings = `-- name: CountCronPings :one
SELECT COUNT(*) FROM cron_pings WHERE monitor_id = $1
`

func (q *Queries) CountCronPings(ctx context.Context, monitorID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCronPings, monitorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCronIncident = `-- name: CreateCronIncident :one
INSERT INTO cron_incidents (monitor_id)
VALUES ($1)
RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) CreateCronIncident(ctx context.Context, monitorID uuid.UUID) (CronIncident, error) {
	row := q.db.QueryRow(ctx, createCronIncident, monitorID)
	var i CronIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const createCronMonitor = `-- name: CreateCronMonitor :one
INSERT INTO cron_monitors (org_id, name, schedule, grace_period_mins, ping_token, max_alerts_per_incident, alert_after_n_failures, max_duration_mins)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins
`

type CreateCronMonitorParams struct {
	OrgID                uuid.UUID   `json:"org_id"`
	Name                 string      `json:"name"`
	Schedule             string      `json:"schedule"`
	GracePeriodMins      int32       `json:"grace_period_mins"`
	PingToken            string      `json:"ping_token"`
	MaxAlertsPerIncident int32       `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32       `json:"alert_after_n_failures"`
	MaxDurationMins      pgtype.Int4 `json:"max_duration_mins"`
}

func (q *Queries) CreateCronMonitor(ctx context.Context, arg CreateCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, createCronMonitor,
		arg.OrgID,
		arg.Name,
		arg.Schedule,
		arg.GracePeriodMins,
		arg.PingToken,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
		arg.MaxDurationMins,
	)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.MaxDurationMins,
	)
	return i, err
}

const createCronPing = `-- name: CreateCronPing :one
INSERT INTO cron_pings (monitor_id, received_at, source_ip, metadata, run_started_at)
VALUES ($1, NOW(), $2, $3, $4)
RETURNING id, monitor_id, received_at, source_ip, metadata, run_started_at
`

type CreateCronPingParams struct {
	MonitorID    uuid.UUID          `json:"monitor_id"`
	SourceIp     string             `json:"source_ip"`
	Metadata     []byte             `json:"metadata"`
	RunStartedAt pgtype.Timestamptz `json:"run_started_at"`
}

func (q *Queries) CreateCronPing(ctx context.Context, arg CreateCronPingParams) (CronPing, error) {
	row := q.db.QueryRow(ctx, createCronPing,
		arg.MonitorID,
		arg.SourceIp,
		arg.Metadata,
		arg.RunStartedAt,
	)
	var i CronPing
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ReceivedAt,
		&i.SourceIp,
		&i.Metadata,
		&i.RunStartedAt,
	)
	return i, err
}

const createCronRun = `-- name: CreateCronRun :one
INSERT INTO cron_runs (monitor_id)
VALUES ($1)
RETURNING id, monitor_id, started_at, completed_at, alerted_at, overlap
`

func (q *Queries) CreateCronRun(ctx context.Context, monitorID uuid.UUID) (CronRun, error) {
	row := q.db.QueryRow(ctx, createCronRun, monitorID)
	var i CronRun
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.AlertedAt,
		&i.Overlap,
	)
	return i, err
}

const deleteCronMonitor = `-- name: DeleteCronMonitor :exec
DELETE FROM cron_monitors WHERE id = $1 AND org_id = $2
`

type DeleteCronMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteCronMonitor(ctx context.Context, arg DeleteCronMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteCronMonitor, arg.ID, arg.OrgID)
	return err
}

const deleteOldCronPings = `-- name: DeleteOldCronPings :exec
DELETE FROM cron_pings WHERE received_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldCronPings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldCronPings)
	return err
}

const deleteOldCronRuns = `-- name: DeleteOldCronRuns :exec
DELETE FROM cron_runs WHERE started_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldCronRuns(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldCronRuns)
	return err
}

const getCronMonitor = `-- name: GetCronMonitor :one
SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins FROM cron_monitors WHERE id = $1 AND org_id = $2
`

type GetCronMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetCronMonitor(ctx context.Context, arg GetCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, getCronMonitor, arg.ID, arg.OrgID)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.MaxDurationMins,
	)
	return i, err
}

const getCronMonitorByToken = `-- name: GetCronMonitorByToken :one
SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins FROM cron_monitors WHERE ping_token = $1
`

func (q *Queries) GetCronMonitorByToken(ctx context.Context, pingToken string) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, getCronMonitorByToken, pingToken)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.MaxDurationMins,
	)
	return i, err
}

const getLatestCronPing = `-- name: GetLatestCronPing :one
SELECT id, monitor_id, received_at, source_ip, metadata, run_started_at FROM cron_pings WHERE monitor_id = $1 ORDER BY received_at DESC LIMIT 1
`

func (q *Queries) GetLatestCronPing(ctx context.Context, monitorID uuid.UUID) (CronPing, error) {
	row := q.db.QueryRow(ctx, getLatestCronPing, monitorID)
	var i CronPing
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ReceivedAt,
		&i.SourceIp,
		&i.Metadata,
		&i.RunStartedAt,
	)
	return i, err
}

const getOpenCronRun = `-- name: GetOpenCronRun :one
SELECT id, monitor_id, started_at, completed_at, alerted_at, overlap FROM cron_runs WHERE monitor_id = $1 AND completed_at IS NULL ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetOpenCronRun(ctx context.Context, monitorID uuid.UUID) (CronRun, error) {
	row := q.db.QueryRow(ctx, getOpenCronRun, monitorID)
	var i CronRun
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.AlertedAt,
		&i.Overlap,
	)
	return i, err
}

const incrementCronConsecutiveFailures = `-- name: IncrementCronConsecutiveFailures :one
UPDATE cron_monitors
SET consecutive_failures = consecutive_failures + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins
`

func (q *Queries) IncrementCronConsecutiveFailures(ctx context.Context, id uuid.UUID) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, incrementCronConsecutiveFailures, id)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.MaxDurationMins,
	)
	return i, err
}

const incrementCronIncidentAlertCount = `-- name: IncrementCronIncidentAlertCount :one
UPDATE cron_incidents SET alert_count = alert_count + 1 WHERE id = $1 RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) IncrementCronIncidentAlertCount(ctx context.Context, id uuid.UUID) (CronIncident, error) {
	row := q.db.QueryRow(ctx, incrementCronIncidentAlertCount, id)
	var i CronIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const listCronIncidents = `-- name: ListCronIncidents :many
SELECT id, monitor_id, started_at, resolved_at, alert_count FROM cron_incidents WHERE monitor_id = $1 ORDER BY started_at DESC LIMIT 200
`

func (q *Queries) ListCronIncidents(ctx context.Context, monitorID uuid.UUID) ([]CronIncident, error) {
	rows, err := q.db.Query(ctx, listCronIncidents, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronIncident{}
	for rows.Next() {
		var i CronIncident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AlertCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronMonitors = `-- name: ListCronMonitors :many
SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins FROM cron_monitors WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCronMonitors(ctx context.Context, orgID uuid.UUID) ([]CronMonitor, error) {
	rows, err := q.db.Query(ctx, listCronMonitors, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronMonitor{}
	for rows.Next() {
		var i CronMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Schedule,
			&i.GracePeriodMins,
			&i.PingToken,
			&i.Status,
			&i.AlertsEnabled,
			&i.LastPingAt,
			&i.NextPingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxAlertsPerIncident,
			&i.AlertAfterNFailures,
			&i.ConsecutiveFailures,
			&i.MaxDurationMins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCronPings = `-- name: ListCronPings :many
SELECT id, monitor_id, received_at, source_ip, metadata, run_started_at FROM cron_pings WHERE monitor_id = $1 ORDER BY received_at DESC LIMIT $2 OFFSET $3
`

type ListCronPingsParams struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListCronPings(ctx context.Context, arg ListCronPingsParams) ([]CronPing, error) {
	rows, err := q.db.Query(ctx, listCronPings, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronPing{}
	for rows.Next() {
		var i CronPing
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ReceivedAt,
			&i.SourceIp,
			&i.Metadata,
			&i.RunStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueCronMonitors = `-- name: ListOverdueCronMonitors :many
SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins FROM cron_monitors
WHERE status = 'up' AND next_ping_at < NOW()
  AND NOT EXISTS (
    SELECT 1 FROM maintenance_window_monitors mwm
    JOIN maintenance_windows mw ON mw.id = mwm.window_id
    WHERE mwm.monitor_type = 'cron' AND mwm.monitor_id = cron_monitors.id
      AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
  )
`

func (q *Queries) ListOverdueCronMonitors(ctx context.Context) ([]CronMonitor, error) {
	rows, err := q.db.Query(ctx, listOverdueCronMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CronMonitor{}
	for rows.Next() {
		var i CronMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Schedule,
			&i.GracePeriodMins,
			&i.PingToken,
			&i.Status,
			&i.AlertsEnabled,
			&i.LastPingAt,
			&i.NextPingAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MaxAlertsPerIncident,
			&i.AlertAfterNFailures,
			&i.ConsecutiveFailures,
			&i.MaxDurationMins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckCronRuns = `-- name: ListStuckCronRuns :many
SELECT cron_runs.id, cron_runs.monitor_id, cron_runs.started_at, cron_runs.completed_at, cron_runs.alerted_at, cron_runs.overlap, cron_monitors.name AS monitor_name, cron_monitors.org_id AS monitor_org_id, cron_monitors.alerts_enabled AS monitor_alerts_enabled, cron_monitors.max_duration_mins AS monitor_max_duration_mins
FROM cron_runs
JOIN cron_monitors ON cron_monitors.id = cron_runs.monitor_id
WHERE cron_runs.completed_at IS NULL
  AND cron_runs.alerted_at IS NULL
  AND cron_monitors.max_duration_mins IS NOT NULL
  AND cron_runs.started_at < NOW() - make_interval(mins => cron_monitors.max_duration_mins)
  AND NOT EXISTS (
    SELECT 1 FROM maintenance_window_monitors mwm
    JOIN maintenance_windows mw ON mw.id = mwm.window_id
    WHERE mwm.monitor_type = 'cron' AND mwm.monitor_id = cron_runs.monitor_id
      AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
  )
`

type ListStuckCronRunsRow struct {
	ID                     uuid.UUID          `json:"id"`
	MonitorID              uuid.UUID          `json:"monitor_id"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CompletedAt            pgtype.Timestamptz `json:"completed_at"`
	AlertedAt              pgtype.Timestamptz `json:"alerted_at"`
	Overlap                bool               `json:"overlap"`
	MonitorName            string             `json:"monitor_name"`
	MonitorOrgID           uuid.UUID          `json:"monitor_org_id"`
	MonitorAlertsEnabled   bool               `json:"monitor_alerts_enabled"`
	MonitorMaxDurationMins pgtype.Int4        `json:"monitor_max_duration_mins"`
}

func (q *Queries) ListStuckCronRuns(ctx context.Context) ([]ListStuckCronRunsRow, error) {
	rows, err := q.db.Query(ctx, listStuckCronRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStuckCronRunsRow{}
	for rows.Next() {
		var i ListStuckCronRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.AlertedAt,
			&i.Overlap,
			&i.MonitorName,
			&i.MonitorOrgID,
			&i.MonitorAlertsEnabled,
			&i.MonitorMaxDurationMins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCronRunAlerted = `-- name: MarkCronRunAlerted :one
UPDATE cron_runs SET alerted_at = NOW() WHERE id = $1 RETURNING id, monitor_id, started_at, completed_at, alerted_at, overlap
`

func (q *Queries) MarkCronRunAlerted(ctx context.Context, id uuid.UUID) (CronRun, error) {
	row := q.db.QueryRow(ctx, markCronRunAlerted, id)
	var i CronRun
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.AlertedAt,
		&i.Overlap,
	)
	return i, err
}

const pauseCronMonitor = `-- name: PauseCronMonitor :one
UPDATE cron_monitors SET status = 'paused', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins
`

type PauseCronMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) PauseCronMonitor(ctx context.Context, arg PauseCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, pauseCronMonitor, arg.ID, arg.OrgID)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.MaxDurationMins,
	)
	return i, err
}

const resolveLatestCronIncident = `-- name: ResolveLatestCronIncident :one
UPDATE cron_incidents
SET resolved_at = NOW()
WHERE id = (
    SELECT ci.id FROM cron_incidents ci
    WHERE ci.monitor_id = $1 AND ci.resolved_at IS NULL
    ORDER BY ci.started_at DESC
    LIMIT 1
)
RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) ResolveLatestCronIncident(ctx context.Context, monitorID uuid.UUID) (CronIncident, error) {
	row := q.db.QueryRow(ctx, resolveLatestCronIncident, monitorID)
	var i CronIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const resumeCronMonitor = `-- name: ResumeCronMonitor :one
UPDATE cron_monitors SET status = 'waiting', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins
`

type ResumeCronMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) ResumeCronMonitor(ctx context.Context, arg ResumeCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, resumeCronMonitor, arg.ID, arg.OrgID)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.MaxDurationMins,
	)
	return i, err
}

const updateCronMonitor = `-- name: UpdateCronMonitor :one
UPDATE cron_monitors
SET name = $3, schedule = $4, grace_period_mins = $5, alerts_enabled = $6, max_alerts_per_incident = $7,
    alert_after_n_failures = $8, max_duration_mins = $9, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins
`

type UpdateCronMonitorParams struct {
	ID                   uuid.UUID   `json:"id"`
	OrgID                uuid.UUID   `json:"org_id"`
	Name                 string      `json:"name"`
	Schedule             string      `json:"schedule"`
	GracePeriodMins      int32       `json:"grace_period_mins"`
	AlertsEnabled        bool        `json:"alerts_enabled"`
	MaxAlertsPerIncident int32       `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32       `json:"alert_after_n_failures"`
	MaxDurationMins      pgtype.Int4 `json:"max_duration_mins"`
}

func (q *Queries) UpdateCronMonitor(ctx context.Context, arg UpdateCronMonitorParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, updateCronMonitor,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Schedule,
		arg.GracePeriodMins,
		arg.AlertsEnabled,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
		arg.MaxDurationMins,
	)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.MaxDurationMins,
	)
	return i, err
}

const updateCronMonitorDown = `-- name: UpdateCronMonitorDown :exec
UPDATE cron_monitors
SET status = 'down', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateCronMonitorDown(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateCronMonitorDown, id)
	return err
}

const updateCronMonitorPing = `-- name: UpdateCronMonitorPing :one
UPDATE cron_monitors
SET status = 'up', last_ping_at = $3, next_ping_at = $4, consecutive_failures = 0, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled, last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, max_duration_mins
`

type UpdateCronMonitorPingParams struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	LastPingAt pgtype.Timestamptz `json:"last_ping_at"`
	NextPingAt pgtype.Timestamptz `json:"next_ping_at"`
}

func (q *Queries) UpdateCronMonitorPing(ctx context.Context, arg UpdateCronMonitorPingParams) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, updateCronMonitorPing,
		arg.ID,
		arg.OrgID,
		arg.LastPingAt,
		arg.NextPingAt,
	)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.MaxDurationMins,
	)
	return i, err
}
