// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationChannel = `-- name: CreateNotificationChannel :one

INSERT INTO notification_channels (org_id, type, name, config)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, type, name, config, enabled, created_at, updated_at, last_delivery_status, last_delivery_detail, last_delivery_at
`

type CreateNotificationChannelParams struct {
	OrgID  uuid.UUID               `json:"org_id"`
	Type   NotificationChannelType `json:"type"`
	Name   string                  `json:"name"`
	Config []byte                  `json:"config"`
}

// ─── notification_channels ───────────────────────────────────────────────────
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.OrgID,
		arg.Type,
		arg.Name,
		arg.Config,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastDeliveryStatus,
		&i.LastDeliveryDetail,
		&i.LastDeliveryAt,
	)
	return i, err
}

const deleteMonitorNotificationChannels = `-- name: DeleteMonitorNotificationChannels :exec
DELETE FROM monitor_notification_channels WHERE monitor_type = $1 AND monitor_id = $2
`

type DeleteMonitorNotificationChannelsParams struct {
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

func (q *Queries) DeleteMonitorNotificationChannels(ctx context.Context, arg DeleteMonitorNotificationChannelsParams) error {
	_, err := q.db.Exec(ctx, deleteMonitorNotificationChannels, arg.MonitorType, arg.MonitorID)
	return err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels WHERE id = $1 AND org_id = $2
`

type DeleteNotificationChannelParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationChannel, arg.ID, arg.OrgID)
	return err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, org_id, type, name, config, enabled, created_at, updated_at, last_delivery_status, last_delivery_detail, last_delivery_at FROM notification_channels WHERE id = $1 AND org_id = $2
`

type GetNotificationChannelParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.OrgID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastDeliveryStatus,
		&i.LastDeliveryDetail,
		&i.LastDeliveryAt,
	)
	return i, err
}

const insertMonitorNotificationChannel = `-- name: InsertMonitorNotificationChannel :exec
INSERT INTO monitor_notification_channels (channel_id, monitor_type, monitor_id)
VALUES ($1, $2, $3)
`

type InsertMonitorNotificationChannelParams struct {
	ChannelID   uuid.UUID `json:"channel_id"`
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

func (q *Queries) InsertMonitorNotificationChannel(ctx context.Context, arg InsertMonitorNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, insertMonitorNotificationChannel, arg.ChannelID, arg.MonitorType, arg.MonitorID)
	return err
}

const listEnabledNotificationChannels = `-- name: ListEnabledNotificationChannels :many
SELECT id, org_id, type, name, config, enabled, created_at, updated_at, last_delivery_status, last_delivery_detail, last_delivery_at FROM notification_channels WHERE org_id = $1 AND enabled = true ORDER BY created_at
`

func (q *Queries) ListEnabledNotificationChannels(ctx context.Context, orgID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledNotificationChannels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastDeliveryStatus,
			&i.LastDeliveryDetail,
			&i.LastDeliveryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorNotificationChannelIDs = `-- name: ListMonitorNotificationChannelIDs :many

SELECT channel_id FROM monitor_notification_channels WHERE monitor_type = $1 AND monitor_id = $2
`

type ListMonitorNotificationChannelIDsParams struct {
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

// ─── monitor_notification_channels ───────────────────────────────────────────
func (q *Queries) ListMonitorNotificationChannelIDs(ctx context.Context, arg ListMonitorNotificationChannelIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMonitorNotificationChannelIDs, arg.MonitorType, arg.MonitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var channel_id uuid.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorNotificationChannels = `-- name: ListMonitorNotificationChannels :many
SELECT nc.id, nc.org_id, nc.type, nc.name, nc.config, nc.enabled, nc.created_at, nc.updated_at, nc.last_delivery_status, nc.last_delivery_detail, nc.last_delivery_at FROM notification_channels nc
JOIN monitor_notification_channels mnc ON mnc.channel_id = nc.id
WHERE mnc.monitor_type = $1 AND mnc.monitor_id = $2 AND nc.enabled = true
`

type ListMonitorNotificationChannelsParams struct {
	MonitorType string    `json:"monitor_type"`
	MonitorID   uuid.UUID `json:"monitor_id"`
}

func (q *Queries) ListMonitorNotificationChannels(ctx context.Context, arg ListMonitorNotificationChannelsParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listMonitorNotificationChannels, arg.MonitorType, arg.MonitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastDeliveryStatus,
			&i.LastDeliveryDetail,
			&i.LastDeliveryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, org_id, type, name, config, enabled, created_at, updated_at, last_delivery_status, last_delivery_detail, last_delivery_at FROM notification_channels WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNotificationChannels(ctx context.Context, orgID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastDeliveryStatus,
			&i.LastDeliveryDetail,
			&i.LastDeliveryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgUserEmails = `-- name: ListOrgUserEmails :many

SELECT email FROM users WHERE org_id = $1
`

// ─── fallback (ADR-023) ───────────────────────────────────────────────────────
func (q *Queries) ListOrgUserEmails(ctx context.Context, orgID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOrgUserEmails, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET name = $3, config = $4, enabled = $5, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, type, name, config, enabled, created_at, updated_at, last_delivery_status, last_delivery_detail, last_delivery_at
`

type UpdateNotificationChannelParams struct {
	ID      uuid.UUID `json:"id"`
	OrgID   uuid.UUID `json:"org_id"`
	Name    string    `json:"name"`
	Config  []byte    `json:"config"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastDeliveryStatus,
		&i.LastDeliveryDetail,
		&i.LastDeliveryAt,
	)
	return i, err
}

const updateNotificationChannelConfig = `-- name: UpdateNotificationChannelConfig :one
UPDATE notification_channels
SET config = $3, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, type, name, config, enabled, created_at, updated_at, last_delivery_status, last_delivery_detail, last_delivery_at
`

type UpdateNotificationChannelConfigParams struct {
	ID     uuid.UUID `json:"id"`
	OrgID  uuid.UUID `json:"org_id"`
	Config []byte    `json:"config"`
}

// Used for regenerating a webhook's signing secret in place, without
// touching name/enabled (US-1403) — UpdateNotificationChannel always
// requires both, which would force the regenerate endpoint to re-send them.
func (q *Queries) UpdateNotificationChannelConfig(ctx context.Context, arg UpdateNotificationChannelConfigParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannelConfig, arg.ID, arg.OrgID, arg.Config)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastDeliveryStatus,
		&i.LastDeliveryDetail,
		&i.LastDeliveryAt,
	)
	return i, err
}

const updateNotificationChannelDelivery = `-- name: UpdateNotificationChannelDelivery :exec
UPDATE notification_channels
SET last_delivery_status = $2, last_delivery_detail = $3, last_delivery_at = NOW()
WHERE id = $1
`

type UpdateNotificationChannelDeliveryParams struct {
	ID                 uuid.UUID   `json:"id"`
	LastDeliveryStatus pgtype.Text `json:"last_delivery_status"`
	LastDeliveryDetail pgtype.Text `json:"last_delivery_detail"`
}

// Records the outcome of the most recent send attempt (US-1404). No org_id
// filter — only called from the worker, which already scoped the channel via
// ListMonitorNotificationChannels, not from a user-facing handler.
func (q *Queries) UpdateNotificationChannelDelivery(ctx context.Context, arg UpdateNotificationChannelDeliveryParams) error {
	_, err := q.db.Exec(ctx, updateNotificationChannelDelivery, arg.ID, arg.LastDeliveryStatus, arg.LastDeliveryDetail)
	return err
}
