// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, plan, created_at, updated_at, telegram_chat_id FROM orgs WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id uuid.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramChatID,
	)
	return i, err
}

const updateOrgTelegramChatID = `-- name: UpdateOrgTelegramChatID :one
UPDATE orgs
SET telegram_chat_id = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, plan, created_at, updated_at, telegram_chat_id
`

type UpdateOrgTelegramChatIDParams struct {
	ID             uuid.UUID   `json:"id"`
	TelegramChatID pgtype.Text `json:"telegram_chat_id"`
}

func (q *Queries) UpdateOrgTelegramChatID(ctx context.Context, arg UpdateOrgTelegramChatIDParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrgTelegramChatID, arg.ID, arg.TelegramChatID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TelegramChatID,
	)
	return i, err
}
