// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: port.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPortCheck = `-- name: CreatePortCheck :one
INSERT INTO port_checks (monitor_id, response_time_ms, is_up, failure_reason)
VALUES ($1, $2, $3, $4)
RETURNING id, monitor_id, checked_at, response_time_ms, is_up, failure_reason
`

type CreatePortCheckParams struct {
	MonitorID      uuid.UUID   `json:"monitor_id"`
	ResponseTimeMs int32       `json:"response_time_ms"`
	IsUp           bool        `json:"is_up"`
	FailureReason  pgtype.Text `json:"failure_reason"`
}

func (q *Queries) CreatePortCheck(ctx context.Context, arg CreatePortCheckParams) (PortCheck, error) {
	row := q.db.QueryRow(ctx, createPortCheck,
		arg.MonitorID,
		arg.ResponseTimeMs,
		arg.IsUp,
		arg.FailureReason,
	)
	var i PortCheck
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.CheckedAt,
		&i.ResponseTimeMs,
		&i.IsUp,
		&i.FailureReason,
	)
	return i, err
}

const createPortIncident = `-- name: CreatePortIncident :one
INSERT INTO port_incidents (monitor_id) VALUES ($1) RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) CreatePortIncident(ctx context.Context, monitorID uuid.UUID) (PortIncident, error) {
	row := q.db.QueryRow(ctx, createPortIncident, monitorID)
	var i PortIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const createPortMonitor = `-- name: CreatePortMonitor :one
INSERT INTO port_monitors (org_id, name, host, port, expected_state, interval_mins, max_alerts_per_incident, alert_after_n_failures)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type CreatePortMonitorParams struct {
	OrgID                uuid.UUID         `json:"org_id"`
	Name                 string            `json:"name"`
	Host                 string            `json:"host"`
	Port                 int32             `json:"port"`
	ExpectedState        PortExpectedState `json:"expected_state"`
	IntervalMins         int32             `json:"interval_mins"`
	MaxAlertsPerIncident int32             `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32             `json:"alert_after_n_failures"`
}

func (q *Queries) CreatePortMonitor(ctx context.Context, arg CreatePortMonitorParams) (PortMonitor, error) {
	row := q.db.QueryRow(ctx, createPortMonitor,
		arg.OrgID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.ExpectedState,
		arg.IntervalMins,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
	)
	var i PortMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.ExpectedState,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldPortChecks = `-- name: DeleteOldPortChecks :exec
DELETE FROM port_checks WHERE checked_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) DeleteOldPortChecks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldPortChecks)
	return err
}

const deletePortMonitor = `-- name: DeletePortMonitor :exec
DELETE FROM port_monitors WHERE id = $1 AND org_id = $2
`

type DeletePortMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeletePortMonitor(ctx context.Context, arg DeletePortMonitorParams) error {
	_, err := q.db.Exec(ctx, deletePortMonitor, arg.ID, arg.OrgID)
	return err
}

const getPortMonitor = `-- name: GetPortMonitor :one
SELECT id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at FROM port_monitors WHERE id = $1 AND org_id = $2
`

type GetPortMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetPortMonitor(ctx context.Context, arg GetPortMonitorParams) (PortMonitor, error) {
	row := q.db.QueryRow(ctx, getPortMonitor, arg.ID, arg.OrgID)
	var i PortMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.ExpectedState,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortStats = `-- name: GetPortStats :one
SELECT
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '24 hours')  AS up_24h,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '24 hours')             AS total_24h,
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '7 days')    AS up_7d,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '7 days')               AS total_7d,
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '30 days')   AS up_30d,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '30 days')              AS total_30d
FROM port_checks
WHERE monitor_id = $1
`

type GetPortStatsRow struct {
	Up24h    int64 `json:"up_24h"`
	Total24h int64 `json:"total_24h"`
	Up7d     int64 `json:"up_7d"`
	Total7d  int64 `json:"total_7d"`
	Up30d    int64 `json:"up_30d"`
	Total30d int64 `json:"total_30d"`
}

func (q *Queries) GetPortStats(ctx context.Context, monitorID uuid.UUID) (GetPortStatsRow, error) {
	row := q.db.QueryRow(ctx, getPortStats, monitorID)
	var i GetPortStatsRow
	err := row.Scan(
		&i.Up24h,
		&i.Total24h,
		&i.Up7d,
		&i.Total7d,
		&i.Up30d,
		&i.Total30d,
	)
	return i, err
}

const incrementPortIncidentAlertCount = `-- name: IncrementPortIncidentAlertCount :one
UPDATE port_incidents SET alert_count = alert_count + 1 WHERE id = $1 RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) IncrementPortIncidentAlertCount(ctx context.Context, id uuid.UUID) (PortIncident, error) {
	row := q.db.QueryRow(ctx, incrementPortIncidentAlertCount, id)
	var i PortIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const listDuePortMonitors = `-- name: ListDuePortMonitors :many
SELECT id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at FROM port_monitors
WHERE next_check_at <= NOW() AND status != 'paused'
  AND NOT EXISTS (
    SELECT 1 FROM maintenance_window_monitors mwm
    JOIN maintenance_windows mw ON mw.id = mwm.window_id
    WHERE mwm.monitor_type = 'port' AND mwm.monitor_id = port_monitors.id
      AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
  )
`

func (q *Queries) ListDuePortMonitors(ctx context.Context) ([]PortMonitor, error) {
	rows, err := q.db.Query(ctx, listDuePortMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortMonitor{}
	for rows.Next() {
		var i PortMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.ExpectedState,
			&i.IntervalMins,
			&i.Status,
			&i.AlertsEnabled,
			&i.MaxAlertsPerIncident,
			&i.AlertAfterNFailures,
			&i.ConsecutiveFailures,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortChecks = `-- name: ListPortChecks :many
SELECT id, monitor_id, checked_at, response_time_ms, is_up, failure_reason FROM port_checks WHERE monitor_id = $1 ORDER BY checked_at DESC LIMIT $2 OFFSET $3
`

type ListPortChecksParams struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListPortChecks(ctx context.Context, arg ListPortChecksParams) ([]PortCheck, error) {
	rows, err := q.db.Query(ctx, listPortChecks, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortCheck{}
	for rows.Next() {
		var i PortCheck
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.CheckedAt,
			&i.ResponseTimeMs,
			&i.IsUp,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortChecks24h = `-- name: ListPortChecks24h :many
SELECT id, monitor_id, checked_at, response_time_ms, is_up, failure_reason FROM port_checks
WHERE monitor_id = $1 AND checked_at >= NOW() - INTERVAL '24 hours'
ORDER BY checked_at ASC
`

func (q *Queries) ListPortChecks24h(ctx context.Context, monitorID uuid.UUID) ([]PortCheck, error) {
	rows, err := q.db.Query(ctx, listPortChecks24h, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortCheck{}
	for rows.Next() {
		var i PortCheck
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.CheckedAt,
			&i.ResponseTimeMs,
			&i.IsUp,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortIncidents = `-- name: ListPortIncidents :many
SELECT id, monitor_id, started_at, resolved_at, alert_count FROM port_incidents WHERE monitor_id = $1 ORDER BY started_at DESC LIMIT 200
`

func (q *Queries) ListPortIncidents(ctx context.Context, monitorID uuid.UUID) ([]PortIncident, error) {
	rows, err := q.db.Query(ctx, listPortIncidents, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortIncident{}
	for rows.Next() {
		var i PortIncident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AlertCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortMonitors = `-- name: ListPortMonitors :many
SELECT id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at FROM port_monitors WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPortMonitors(ctx context.Context, orgID uuid.UUID) ([]PortMonitor, error) {
	rows, err := q.db.Query(ctx, listPortMonitors, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortMonitor{}
	for rows.Next() {
		var i PortMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.ExpectedState,
			&i.IntervalMins,
			&i.Status,
			&i.AlertsEnabled,
			&i.MaxAlertsPerIncident,
			&i.AlertAfterNFailures,
			&i.ConsecutiveFailures,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPortMonitorDown = `-- name: MarkPortMonitorDown :exec
UPDATE port_monitors SET status = 'down', updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkPortMonitorDown(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPortMonitorDown, id)
	return err
}

const pausePortMonitor = `-- name: PausePortMonitor :one
UPDATE port_monitors SET status = 'paused', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type PausePortMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) PausePortMonitor(ctx context.Context, arg PausePortMonitorParams) (PortMonitor, error) {
	row := q.db.QueryRow(ctx, pausePortMonitor, arg.ID, arg.OrgID)
	var i PortMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.ExpectedState,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPortCheckFailure = `-- name: RecordPortCheckFailure :one
UPDATE port_monitors
SET consecutive_failures = consecutive_failures + 1,
    last_checked_at = NOW(),
    next_check_at = NOW() + (interval_mins * INTERVAL '1 minute'),
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

func (q *Queries) RecordPortCheckFailure(ctx context.Context, id uuid.UUID) (PortMonitor, error) {
	row := q.db.QueryRow(ctx, recordPortCheckFailure, id)
	var i PortMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.ExpectedState,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPortCheckUp = `-- name: RecordPortCheckUp :one
UPDATE port_monitors
SET status = 'up',
    consecutive_failures = 0,
    last_checked_at = NOW(),
    next_check_at = NOW() + (interval_mins * INTERVAL '1 minute'),
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

func (q *Queries) RecordPortCheckUp(ctx context.Context, id uuid.UUID) (PortMonitor, error) {
	row := q.db.QueryRow(ctx, recordPortCheckUp, id)
	var i PortMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.ExpectedState,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveLatestPortIncident = `-- name: ResolveLatestPortIncident :one
UPDATE port_incidents
SET resolved_at = NOW()
WHERE id = (
    SELECT pi.id FROM port_incidents pi
    WHERE pi.monitor_id = $1 AND pi.resolved_at IS NULL
    ORDER BY pi.started_at DESC
    LIMIT 1
)
RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) ResolveLatestPortIncident(ctx context.Context, monitorID uuid.UUID) (PortIncident, error) {
	row := q.db.QueryRow(ctx, resolveLatestPortIncident, monitorID)
	var i PortIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const resumePortMonitor = `-- name: ResumePortMonitor :one
UPDATE port_monitors SET status = 'waiting', next_check_at = NOW(), updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type ResumePortMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) ResumePortMonitor(ctx context.Context, arg ResumePortMonitorParams) (PortMonitor, error) {
	row := q.db.QueryRow(ctx, resumePortMonitor, arg.ID, arg.OrgID)
	var i PortMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.ExpectedState,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePortMonitor = `-- name: UpdatePortMonitor :one
UPDATE port_monitors
SET name = $3, host = $4, port = $5, expected_state = $6, interval_mins = $7, alerts_enabled = $8,
    max_alerts_per_incident = $9, alert_after_n_failures = $10, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, host, port, expected_state, interval_mins, status, alerts_enabled, max_alerts_per_incident, alert_after_n_failures, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at
`

type UpdatePortMonitorParams struct {
	ID                   uuid.UUID         `json:"id"`
	OrgID                uuid.UUID         `json:"org_id"`
	Name                 string            `json:"name"`
	Host                 string            `json:"host"`
	Port                 int32             `json:"port"`
	ExpectedState        PortExpectedState `json:"expected_state"`
	IntervalMins         int32             `json:"interval_mins"`
	AlertsEnabled        bool              `json:"alerts_enabled"`
	MaxAlertsPerIncident int32             `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32             `json:"alert_after_n_failures"`
}

func (q *Queries) UpdatePortMonitor(ctx context.Context, arg UpdatePortMonitorParams) (PortMonitor, error) {
	row := q.db.QueryRow(ctx, updatePortMonitor,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.ExpectedState,
		arg.IntervalMins,
		arg.AlertsEnabled,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
	)
	var i PortMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.ExpectedState,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.AlertAfterNFailures,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
