// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssl.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSSLMonitor = `-- name: CreateSSLMonitor :one
INSERT INTO ssl_monitors (org_id, name, hostname)
VALUES ($1, $2, $3)
RETURNING id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type CreateSSLMonitorParams struct {
	OrgID    uuid.UUID `json:"org_id"`
	Name     string    `json:"name"`
	Hostname string    `json:"hostname"`
}

func (q *Queries) CreateSSLMonitor(ctx context.Context, arg CreateSSLMonitorParams) (SslMonitor, error) {
	row := q.db.QueryRow(ctx, createSSLMonitor, arg.OrgID, arg.Name, arg.Hostname)
	var i SslMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Issuer,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSSLMonitor = `-- name: DeleteSSLMonitor :exec
DELETE FROM ssl_monitors WHERE id = $1 AND org_id = $2
`

type DeleteSSLMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteSSLMonitor(ctx context.Context, arg DeleteSSLMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteSSLMonitor, arg.ID, arg.OrgID)
	return err
}

const getSSLMonitor = `-- name: GetSSLMonitor :one
SELECT id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at FROM ssl_monitors WHERE id = $1 AND org_id = $2
`

type GetSSLMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetSSLMonitor(ctx context.Context, arg GetSSLMonitorParams) (SslMonitor, error) {
	row := q.db.QueryRow(ctx, getSSLMonitor, arg.ID, arg.OrgID)
	var i SslMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Issuer,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueSSLMonitors = `-- name: ListDueSSLMonitors :many
SELECT id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at FROM ssl_monitors
WHERE next_check_at <= NOW() AND status != 'paused'
  AND NOT EXISTS (
    SELECT 1 FROM maintenance_window_monitors mwm
    JOIN maintenance_windows mw ON mw.id = mwm.window_id
    WHERE mwm.monitor_type = 'ssl' AND mwm.monitor_id = ssl_monitors.id
      AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
  )
`

func (q *Queries) ListDueSSLMonitors(ctx context.Context) ([]SslMonitor, error) {
	rows, err := q.db.Query(ctx, listDueSSLMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SslMonitor{}
	for rows.Next() {
		var i SslMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Hostname,
			&i.Status,
			&i.AlertsEnabled,
			&i.ExpiresAt,
			&i.Issuer,
			&i.ErrorMsg,
			&i.Alerted30d,
			&i.Alerted14d,
			&i.Alerted7d,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSLMonitors = `-- name: ListSSLMonitors :many
SELECT id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at FROM ssl_monitors WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSSLMonitors(ctx context.Context, orgID uuid.UUID) ([]SslMonitor, error) {
	rows, err := q.db.Query(ctx, listSSLMonitors, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SslMonitor{}
	for rows.Next() {
		var i SslMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Hostname,
			&i.Status,
			&i.AlertsEnabled,
			&i.ExpiresAt,
			&i.Issuer,
			&i.ErrorMsg,
			&i.Alerted30d,
			&i.Alerted14d,
			&i.Alerted7d,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseSSLMonitor = `-- name: PauseSSLMonitor :one
UPDATE ssl_monitors SET status = 'paused', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type PauseSSLMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) PauseSSLMonitor(ctx context.Context, arg PauseSSLMonitorParams) (SslMonitor, error) {
	row := q.db.QueryRow(ctx, pauseSSLMonitor, arg.ID, arg.OrgID)
	var i SslMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Issuer,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeSSLMonitor = `-- name: ResumeSSLMonitor :one
UPDATE ssl_monitors SET status = 'waiting', next_check_at = NOW(), updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type ResumeSSLMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) ResumeSSLMonitor(ctx context.Context, arg ResumeSSLMonitorParams) (SslMonitor, error) {
	row := q.db.QueryRow(ctx, resumeSSLMonitor, arg.ID, arg.OrgID)
	var i SslMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Issuer,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSSLMonitor = `-- name: UpdateSSLMonitor :one
UPDATE ssl_monitors
SET name = $3, hostname = $4, alerts_enabled = $5, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type UpdateSSLMonitorParams struct {
	ID            uuid.UUID `json:"id"`
	OrgID         uuid.UUID `json:"org_id"`
	Name          string    `json:"name"`
	Hostname      string    `json:"hostname"`
	AlertsEnabled bool      `json:"alerts_enabled"`
}

func (q *Queries) UpdateSSLMonitor(ctx context.Context, arg UpdateSSLMonitorParams) (SslMonitor, error) {
	row := q.db.QueryRow(ctx, updateSSLMonitor,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Hostname,
		arg.AlertsEnabled,
	)
	var i SslMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Issuer,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSSLMonitorCheck = `-- name: UpdateSSLMonitorCheck :one
UPDATE ssl_monitors
SET status          = $2,
    expires_at      = $3,
    issuer          = $4,
    error_msg       = $5,
    alerted_30d     = $6,
    alerted_14d     = $7,
    alerted_7d      = $8,
    last_checked_at = NOW(),
    next_check_at   = NOW() + INTERVAL '24 hours',
    updated_at      = NOW()
WHERE id = $1
RETURNING id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at
`

type UpdateSSLMonitorCheckParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     SslMonitorStatus   `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Issuer     pgtype.Text        `json:"issuer"`
	ErrorMsg   pgtype.Text        `json:"error_msg"`
	Alerted30d bool               `json:"alerted_30d"`
	Alerted14d bool               `json:"alerted_14d"`
	Alerted7d  bool               `json:"alerted_7d"`
}

func (q *Queries) UpdateSSLMonitorCheck(ctx context.Context, arg UpdateSSLMonitorCheckParams) (SslMonitor, error) {
	row := q.db.QueryRow(ctx, updateSSLMonitorCheck,
		arg.ID,
		arg.Status,
		arg.ExpiresAt,
		arg.Issuer,
		arg.ErrorMsg,
		arg.Alerted30d,
		arg.Alerted14d,
		arg.Alerted7d,
	)
	var i SslMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Issuer,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
