// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_pages.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStatusPage = `-- name: CreateStatusPage :one

INSERT INTO status_pages (org_id, slug, title, description, logo_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, slug, title, description, logo_url, created_at, updated_at
`

type CreateStatusPageParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	LogoUrl     string    `json:"logo_url"`
}

// ─── status_pages ────────────────────────────────────────────────────────────
func (q *Queries) CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, createStatusPage,
		arg.OrgID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.LogoUrl,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStatusPage = `-- name: DeleteStatusPage :exec
DELETE FROM status_pages WHERE id = $1 AND org_id = $2
`

type DeleteStatusPageParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteStatusPage(ctx context.Context, arg DeleteStatusPageParams) error {
	_, err := q.db.Exec(ctx, deleteStatusPage, arg.ID, arg.OrgID)
	return err
}

const deleteStatusPageMonitors = `-- name: DeleteStatusPageMonitors :exec
DELETE FROM status_page_monitors WHERE page_id = $1
`

func (q *Queries) DeleteStatusPageMonitors(ctx context.Context, pageID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStatusPageMonitors, pageID)
	return err
}

const getCronIncidentDays90d = `-- name: GetCronIncidentDays90d :many
SELECT DISTINCT date_trunc('day', started_at AT TIME ZONE 'UTC')::date AS day
FROM cron_incidents
WHERE monitor_id = $1 AND started_at >= NOW() - INTERVAL '90 days'
ORDER BY 1 ASC
`

func (q *Queries) GetCronIncidentDays90d(ctx context.Context, monitorID uuid.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, getCronIncidentDays90d, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var day pgtype.Date
		if err := rows.Scan(&day); err != nil {
			return nil, err
		}
		items = append(items, day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCronMonitorPublic = `-- name: GetCronMonitorPublic :one

SELECT id, org_id, name, schedule, grace_period_mins, ping_token, status, alerts_enabled,
       last_ping_at, next_ping_at, created_at, updated_at, max_alerts_per_incident
FROM cron_monitors WHERE id = $1
`

// Public look-ups (no org_id check — page ownership already verified by slug)
func (q *Queries) GetCronMonitorPublic(ctx context.Context, id uuid.UUID) (CronMonitor, error) {
	row := q.db.QueryRow(ctx, getCronMonitorPublic, id)
	var i CronMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Schedule,
		&i.GracePeriodMins,
		&i.PingToken,
		&i.Status,
		&i.AlertsEnabled,
		&i.LastPingAt,
		&i.NextPingAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MaxAlertsPerIncident,
	)
	return i, err
}

const getDomainMonitorPublic = `-- name: GetDomainMonitorPublic :one
SELECT id, org_id, name, domain, status, alerts_enabled, expires_at, registrar, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at FROM domain_monitors WHERE id = $1
`

func (q *Queries) GetDomainMonitorPublic(ctx context.Context, id uuid.UUID) (DomainMonitor, error) {
	row := q.db.QueryRow(ctx, getDomainMonitorPublic, id)
	var i DomainMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Domain,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Registrar,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSLMonitorPublic = `-- name: GetSSLMonitorPublic :one
SELECT id, org_id, name, hostname, status, alerts_enabled, expires_at, issuer, error_msg, alerted_30d, alerted_14d, alerted_7d, last_checked_at, next_check_at, created_at, updated_at FROM ssl_monitors WHERE id = $1
`

func (q *Queries) GetSSLMonitorPublic(ctx context.Context, id uuid.UUID) (SslMonitor, error) {
	row := q.db.QueryRow(ctx, getSSLMonitorPublic, id)
	var i SslMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Hostname,
		&i.Status,
		&i.AlertsEnabled,
		&i.ExpiresAt,
		&i.Issuer,
		&i.ErrorMsg,
		&i.Alerted30d,
		&i.Alerted14d,
		&i.Alerted7d,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPage = `-- name: GetStatusPage :one
SELECT id, org_id, slug, title, description, logo_url, created_at, updated_at FROM status_pages WHERE id = $1 AND org_id = $2
`

type GetStatusPageParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetStatusPage(ctx context.Context, arg GetStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPage, arg.ID, arg.OrgID)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatusPageBySlug = `-- name: GetStatusPageBySlug :one
SELECT id, org_id, slug, title, description, logo_url, created_at, updated_at FROM status_pages WHERE slug = $1
`

func (q *Queries) GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error) {
	row := q.db.QueryRow(ctx, getStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUptimeDailyStatus90d = `-- name: GetUptimeDailyStatus90d :many

SELECT
    date_trunc('day', checked_at AT TIME ZONE 'UTC')::date AS day,
    COUNT(*) FILTER (WHERE NOT is_up)                       AS down_count
FROM uptime_checks
WHERE monitor_id = $1 AND checked_at >= NOW() - INTERVAL '90 days'
GROUP BY 1
ORDER BY 1 ASC
`

type GetUptimeDailyStatus90dRow struct {
	Day       pgtype.Date `json:"day"`
	DownCount int64       `json:"down_count"`
}

// ─── 90-day bars for public page ─────────────────────────────────────────────
func (q *Queries) GetUptimeDailyStatus90d(ctx context.Context, monitorID uuid.UUID) ([]GetUptimeDailyStatus90dRow, error) {
	rows, err := q.db.Query(ctx, getUptimeDailyStatus90d, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUptimeDailyStatus90dRow{}
	for rows.Next() {
		var i GetUptimeDailyStatus90dRow
		if err := rows.Scan(&i.Day, &i.DownCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUptimeMonitorPublic = `-- name: GetUptimeMonitorPublic :one
SELECT id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive FROM uptime_monitors WHERE id = $1
`

func (q *Queries) GetUptimeMonitorPublic(ctx context.Context, id uuid.UUID) (UptimeMonitor, error) {
	row := q.db.QueryRow(ctx, getUptimeMonitorPublic, id)
	var i UptimeMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordCaseSensitive,
	)
	return i, err
}

const insertStatusPageMonitor = `-- name: InsertStatusPageMonitor :one
INSERT INTO status_page_monitors (page_id, monitor_type, monitor_id, display_name, display_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, page_id, monitor_type, monitor_id, display_name, display_order
`

type InsertStatusPageMonitorParams struct {
	PageID       uuid.UUID `json:"page_id"`
	MonitorType  string    `json:"monitor_type"`
	MonitorID    uuid.UUID `json:"monitor_id"`
	DisplayName  string    `json:"display_name"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) InsertStatusPageMonitor(ctx context.Context, arg InsertStatusPageMonitorParams) (StatusPageMonitor, error) {
	row := q.db.QueryRow(ctx, insertStatusPageMonitor,
		arg.PageID,
		arg.MonitorType,
		arg.MonitorID,
		arg.DisplayName,
		arg.DisplayOrder,
	)
	var i StatusPageMonitor
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.MonitorType,
		&i.MonitorID,
		&i.DisplayName,
		&i.DisplayOrder,
	)
	return i, err
}

const listStatusPageMonitors = `-- name: ListStatusPageMonitors :many

SELECT id, page_id, monitor_type, monitor_id, display_name, display_order FROM status_page_monitors WHERE page_id = $1 ORDER BY display_order ASC
`

// ─── status_page_monitors ────────────────────────────────────────────────────
func (q *Queries) ListStatusPageMonitors(ctx context.Context, pageID uuid.UUID) ([]StatusPageMonitor, error) {
	rows, err := q.db.Query(ctx, listStatusPageMonitors, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageMonitor{}
	for rows.Next() {
		var i StatusPageMonitor
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.MonitorType,
			&i.MonitorID,
			&i.DisplayName,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatusPages = `-- name: ListStatusPages :many
SELECT id, org_id, slug, title, description, logo_url, created_at, updated_at FROM status_pages WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListStatusPages(ctx context.Context, orgID uuid.UUID) ([]StatusPage, error) {
	rows, err := q.db.Query(ctx, listStatusPages, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPage{}
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const slugAvailable = `-- name: SlugAvailable :one
SELECT NOT EXISTS (SELECT 1 FROM status_pages WHERE slug = $1) AS available
`

func (q *Queries) SlugAvailable(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugAvailable, slug)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const updateStatusPage = `-- name: UpdateStatusPage :one
UPDATE status_pages
SET title = $3, description = $4, logo_url = $5, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, slug, title, description, logo_url, created_at, updated_at
`

type UpdateStatusPageParams struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	LogoUrl     string    `json:"logo_url"`
}

func (q *Queries) UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRow(ctx, updateStatusPage,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Description,
		arg.LogoUrl,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
