// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suggestions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFeatureSuggestion = `-- name: CreateFeatureSuggestion :one
INSERT INTO feature_suggestions (org_id, user_id, text)
VALUES ($1, $2, $3)
RETURNING id, org_id, user_id, text, created_at
`

type CreateFeatureSuggestionParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Text   string    `json:"text"`
}

func (q *Queries) CreateFeatureSuggestion(ctx context.Context, arg CreateFeatureSuggestionParams) (FeatureSuggestion, error) {
	row := q.db.QueryRow(ctx, createFeatureSuggestion, arg.OrgID, arg.UserID, arg.Text)
	var i FeatureSuggestion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
