// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uptime.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUptimeMonitors = `-- name: CountUptimeMonitors :one
SELECT COUNT(*) FROM uptime_monitors WHERE org_id = $1
`

func (q *Queries) CountUptimeMonitors(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUptimeMonitors, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUptimeCheck = `-- name: CreateUptimeCheck :one
INSERT INTO uptime_checks (monitor_id, status_code, response_time_ms, is_up, failure_reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, monitor_id, checked_at, status_code, response_time_ms, is_up, failure_reason
`

type CreateUptimeCheckParams struct {
	MonitorID      uuid.UUID   `json:"monitor_id"`
	StatusCode     pgtype.Int4 `json:"status_code"`
	ResponseTimeMs int32       `json:"response_time_ms"`
	IsUp           bool        `json:"is_up"`
	FailureReason  pgtype.Text `json:"failure_reason"`
}

func (q *Queries) CreateUptimeCheck(ctx context.Context, arg CreateUptimeCheckParams) (UptimeCheck, error) {
	row := q.db.QueryRow(ctx, createUptimeCheck,
		arg.MonitorID,
		arg.StatusCode,
		arg.ResponseTimeMs,
		arg.IsUp,
		arg.FailureReason,
	)
	var i UptimeCheck
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.CheckedAt,
		&i.StatusCode,
		&i.ResponseTimeMs,
		&i.IsUp,
		&i.FailureReason,
	)
	return i, err
}

const createUptimeIncident = `-- name: CreateUptimeIncident :one
INSERT INTO uptime_incidents (monitor_id) VALUES ($1) RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) CreateUptimeIncident(ctx context.Context, monitorID uuid.UUID) (UptimeIncident, error) {
	row := q.db.QueryRow(ctx, createUptimeIncident, monitorID)
	var i UptimeIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const createUptimeMonitor = `-- name: CreateUptimeMonitor :one
INSERT INTO uptime_monitors (org_id, name, url, interval_mins, max_alerts_per_incident, alert_after_n_failures, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures
`

type CreateUptimeMonitorParams struct {
	OrgID                uuid.UUID   `json:"org_id"`
	Name                 string      `json:"name"`
	Url                  string      `json:"url"`
	IntervalMins         int32       `json:"interval_mins"`
	MaxAlertsPerIncident int32       `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32       `json:"alert_after_n_failures"`
	Keyword              pgtype.Text `json:"keyword"`
	KeywordMode          KeywordMode `json:"keyword_mode"`
	KeywordCaseSensitive bool        `json:"keyword_case_sensitive"`
	JsonAssertions       []byte      `json:"json_assertions"`
	MaxResponseTimeMs    pgtype.Int4 `json:"max_response_time_ms"`
}

func (q *Queries) CreateUptimeMonitor(ctx context.Context, arg CreateUptimeMonitorParams) (UptimeMonitor, error) {
	row := q.db.QueryRow(ctx, createUptimeMonitor,
		arg.OrgID,
		arg.Name,
		arg.Url,
		arg.IntervalMins,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
		arg.Keyword,
		arg.KeywordMode,
		arg.KeywordCaseSensitive,
		arg.JsonAssertions,
		arg.MaxResponseTimeMs,
	)
	var i UptimeMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordCaseSensitive,
		&i.JsonAssertions,
		&i.MaxResponseTimeMs,
		&i.AlertAfterNFailures,
	)
	return i, err
}

const deleteOldUptimeChecks = `-- name: DeleteOldUptimeChecks :exec
DELETE FROM uptime_checks WHERE checked_at < NOW() - INTERVAL '90 days'
`

func (q *Queries) DeleteOldUptimeChecks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldUptimeChecks)
	return err
}

const deleteUptimeMonitor = `-- name: DeleteUptimeMonitor :exec
DELETE FROM uptime_monitors WHERE id = $1 AND org_id = $2
`

type DeleteUptimeMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteUptimeMonitor(ctx context.Context, arg DeleteUptimeMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteUptimeMonitor, arg.ID, arg.OrgID)
	return err
}

const getUptimeMonitor = `-- name: GetUptimeMonitor :one
SELECT id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures FROM uptime_monitors WHERE id = $1 AND org_id = $2
`

type GetUptimeMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetUptimeMonitor(ctx context.Context, arg GetUptimeMonitorParams) (UptimeMonitor, error) {
	row := q.db.QueryRow(ctx, getUptimeMonitor, arg.ID, arg.OrgID)
	var i UptimeMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordCaseSensitive,
		&i.JsonAssertions,
		&i.MaxResponseTimeMs,
		&i.AlertAfterNFailures,
	)
	return i, err
}

const getUptimeStats = `-- name: GetUptimeStats :one
SELECT
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '24 hours')  AS up_24h,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '24 hours')             AS total_24h,
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '7 days')    AS up_7d,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '7 days')               AS total_7d,
    COUNT(*) FILTER (WHERE is_up AND checked_at >= NOW() - INTERVAL '30 days')   AS up_30d,
    COUNT(*) FILTER (WHERE checked_at >= NOW() - INTERVAL '30 days')              AS total_30d
FROM uptime_checks
WHERE monitor_id = $1
`

type GetUptimeStatsRow struct {
	Up24h    int64 `json:"up_24h"`
	Total24h int64 `json:"total_24h"`
	Up7d     int64 `json:"up_7d"`
	Total7d  int64 `json:"total_7d"`
	Up30d    int64 `json:"up_30d"`
	Total30d int64 `json:"total_30d"`
}

func (q *Queries) GetUptimeStats(ctx context.Context, monitorID uuid.UUID) (GetUptimeStatsRow, error) {
	row := q.db.QueryRow(ctx, getUptimeStats, monitorID)
	var i GetUptimeStatsRow
	err := row.Scan(
		&i.Up24h,
		&i.Total24h,
		&i.Up7d,
		&i.Total7d,
		&i.Up30d,
		&i.Total30d,
	)
	return i, err
}

const incrementUptimeIncidentAlertCount = `-- name: IncrementUptimeIncidentAlertCount :one
UPDATE uptime_incidents SET alert_count = alert_count + 1 WHERE id = $1 RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) IncrementUptimeIncidentAlertCount(ctx context.Context, id uuid.UUID) (UptimeIncident, error) {
	row := q.db.QueryRow(ctx, incrementUptimeIncidentAlertCount, id)
	var i UptimeIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const listDueUptimeMonitors = `-- name: ListDueUptimeMonitors :many
SELECT id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures FROM uptime_monitors
WHERE next_check_at <= NOW() AND status != 'paused'
  AND NOT EXISTS (
    SELECT 1 FROM maintenance_window_monitors mwm
    JOIN maintenance_windows mw ON mw.id = mwm.window_id
    WHERE mwm.monitor_type = 'uptime' AND mwm.monitor_id = uptime_monitors.id
      AND mw.starts_at <= NOW() AND (mw.ends_at IS NULL OR mw.ends_at > NOW())
  )
`

func (q *Queries) ListDueUptimeMonitors(ctx context.Context) ([]UptimeMonitor, error) {
	rows, err := q.db.Query(ctx, listDueUptimeMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeMonitor{}
	for rows.Next() {
		var i UptimeMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Url,
			&i.IntervalMins,
			&i.Status,
			&i.AlertsEnabled,
			&i.MaxAlertsPerIncident,
			&i.ConsecutiveFailures,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.KeywordCaseSensitive,
			&i.JsonAssertions,
			&i.MaxResponseTimeMs,
			&i.AlertAfterNFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeChecks = `-- name: ListUptimeChecks :many
SELECT id, monitor_id, checked_at, status_code, response_time_ms, is_up, failure_reason FROM uptime_checks WHERE monitor_id = $1 ORDER BY checked_at DESC LIMIT $2 OFFSET $3
`

type ListUptimeChecksParams struct {
	MonitorID uuid.UUID `json:"monitor_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListUptimeChecks(ctx context.Context, arg ListUptimeChecksParams) ([]UptimeCheck, error) {
	rows, err := q.db.Query(ctx, listUptimeChecks, arg.MonitorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeCheck{}
	for rows.Next() {
		var i UptimeCheck
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.CheckedAt,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.IsUp,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeChecks24h = `-- name: ListUptimeChecks24h :many
SELECT id, monitor_id, checked_at, status_code, response_time_ms, is_up, failure_reason FROM uptime_checks
WHERE monitor_id = $1 AND checked_at >= NOW() - INTERVAL '24 hours'
ORDER BY checked_at ASC
`

func (q *Queries) ListUptimeChecks24h(ctx context.Context, monitorID uuid.UUID) ([]UptimeCheck, error) {
	rows, err := q.db.Query(ctx, listUptimeChecks24h, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeCheck{}
	for rows.Next() {
		var i UptimeCheck
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.CheckedAt,
			&i.StatusCode,
			&i.ResponseTimeMs,
			&i.IsUp,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeIncidents = `-- name: ListUptimeIncidents :many
SELECT id, monitor_id, started_at, resolved_at, alert_count FROM uptime_incidents WHERE monitor_id = $1 ORDER BY started_at DESC LIMIT 200
`

func (q *Queries) ListUptimeIncidents(ctx context.Context, monitorID uuid.UUID) ([]UptimeIncident, error) {
	rows, err := q.db.Query(ctx, listUptimeIncidents, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeIncident{}
	for rows.Next() {
		var i UptimeIncident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AlertCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUptimeMonitors = `-- name: ListUptimeMonitors :many
SELECT id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures FROM uptime_monitors WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUptimeMonitors(ctx context.Context, orgID uuid.UUID) ([]UptimeMonitor, error) {
	rows, err := q.db.Query(ctx, listUptimeMonitors, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UptimeMonitor{}
	for rows.Next() {
		var i UptimeMonitor
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Url,
			&i.IntervalMins,
			&i.Status,
			&i.AlertsEnabled,
			&i.MaxAlertsPerIncident,
			&i.ConsecutiveFailures,
			&i.LastCheckedAt,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Keyword,
			&i.KeywordMode,
			&i.KeywordCaseSensitive,
			&i.JsonAssertions,
			&i.MaxResponseTimeMs,
			&i.AlertAfterNFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUptimeMonitorDown = `-- name: MarkUptimeMonitorDown :exec
UPDATE uptime_monitors SET status = 'down', updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkUptimeMonitorDown(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUptimeMonitorDown, id)
	return err
}

const pauseUptimeMonitor = `-- name: PauseUptimeMonitor :one
UPDATE uptime_monitors SET status = 'paused', updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures
`

type PauseUptimeMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) PauseUptimeMonitor(ctx context.Context, arg PauseUptimeMonitorParams) (UptimeMonitor, error) {
	row := q.db.QueryRow(ctx, pauseUptimeMonitor, arg.ID, arg.OrgID)
	var i UptimeMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordCaseSensitive,
		&i.JsonAssertions,
		&i.MaxResponseTimeMs,
		&i.AlertAfterNFailures,
	)
	return i, err
}

const recordUptimeCheckFailure = `-- name: RecordUptimeCheckFailure :one
UPDATE uptime_monitors
SET consecutive_failures = consecutive_failures + 1,
    last_checked_at = NOW(),
    next_check_at = NOW() + (interval_mins * INTERVAL '1 minute'),
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures
`

func (q *Queries) RecordUptimeCheckFailure(ctx context.Context, id uuid.UUID) (UptimeMonitor, error) {
	row := q.db.QueryRow(ctx, recordUptimeCheckFailure, id)
	var i UptimeMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordCaseSensitive,
		&i.JsonAssertions,
		&i.MaxResponseTimeMs,
		&i.AlertAfterNFailures,
	)
	return i, err
}

const recordUptimeCheckUp = `-- name: RecordUptimeCheckUp :one
UPDATE uptime_monitors
SET status = 'up',
    consecutive_failures = 0,
    last_checked_at = NOW(),
    next_check_at = NOW() + (interval_mins * INTERVAL '1 minute'),
    updated_at = NOW()
WHERE id = $1
RETURNING id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures
`

func (q *Queries) RecordUptimeCheckUp(ctx context.Context, id uuid.UUID) (UptimeMonitor, error) {
	row := q.db.QueryRow(ctx, recordUptimeCheckUp, id)
	var i UptimeMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordCaseSensitive,
		&i.JsonAssertions,
		&i.MaxResponseTimeMs,
		&i.AlertAfterNFailures,
	)
	return i, err
}

const resolveLatestUptimeIncident = `-- name: ResolveLatestUptimeIncident :one
UPDATE uptime_incidents
SET resolved_at = NOW()
WHERE id = (
    SELECT ui.id FROM uptime_incidents ui
    WHERE ui.monitor_id = $1 AND ui.resolved_at IS NULL
    ORDER BY ui.started_at DESC
    LIMIT 1
)
RETURNING id, monitor_id, started_at, resolved_at, alert_count
`

func (q *Queries) ResolveLatestUptimeIncident(ctx context.Context, monitorID uuid.UUID) (UptimeIncident, error) {
	row := q.db.QueryRow(ctx, resolveLatestUptimeIncident, monitorID)
	var i UptimeIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AlertCount,
	)
	return i, err
}

const resumeUptimeMonitor = `-- name: ResumeUptimeMonitor :one
UPDATE uptime_monitors SET status = 'waiting', next_check_at = NOW(), updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures
`

type ResumeUptimeMonitorParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) ResumeUptimeMonitor(ctx context.Context, arg ResumeUptimeMonitorParams) (UptimeMonitor, error) {
	row := q.db.QueryRow(ctx, resumeUptimeMonitor, arg.ID, arg.OrgID)
	var i UptimeMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordCaseSensitive,
		&i.JsonAssertions,
		&i.MaxResponseTimeMs,
		&i.AlertAfterNFailures,
	)
	return i, err
}

const updateUptimeMonitor = `-- name: UpdateUptimeMonitor :one
UPDATE uptime_monitors
SET name = $3, url = $4, interval_mins = $5, alerts_enabled = $6, max_alerts_per_incident = $7,
    alert_after_n_failures = $8, keyword = $9, keyword_mode = $10, keyword_case_sensitive = $11,
    json_assertions = $12, max_response_time_ms = $13, updated_at = NOW()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, url, interval_mins, status, alerts_enabled, max_alerts_per_incident, consecutive_failures, last_checked_at, next_check_at, created_at, updated_at, keyword, keyword_mode, keyword_case_sensitive, json_assertions, max_response_time_ms, alert_after_n_failures
`

type UpdateUptimeMonitorParams struct {
	ID                   uuid.UUID   `json:"id"`
	OrgID                uuid.UUID   `json:"org_id"`
	Name                 string      `json:"name"`
	Url                  string      `json:"url"`
	IntervalMins         int32       `json:"interval_mins"`
	AlertsEnabled        bool        `json:"alerts_enabled"`
	MaxAlertsPerIncident int32       `json:"max_alerts_per_incident"`
	AlertAfterNFailures  int32       `json:"alert_after_n_failures"`
	Keyword              pgtype.Text `json:"keyword"`
	KeywordMode          KeywordMode `json:"keyword_mode"`
	KeywordCaseSensitive bool        `json:"keyword_case_sensitive"`
	JsonAssertions       []byte      `json:"json_assertions"`
	MaxResponseTimeMs    pgtype.Int4 `json:"max_response_time_ms"`
}

func (q *Queries) UpdateUptimeMonitor(ctx context.Context, arg UpdateUptimeMonitorParams) (UptimeMonitor, error) {
	row := q.db.QueryRow(ctx, updateUptimeMonitor,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Url,
		arg.IntervalMins,
		arg.AlertsEnabled,
		arg.MaxAlertsPerIncident,
		arg.AlertAfterNFailures,
		arg.Keyword,
		arg.KeywordMode,
		arg.KeywordCaseSensitive,
		arg.JsonAssertions,
		arg.MaxResponseTimeMs,
	)
	var i UptimeMonitor
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Url,
		&i.IntervalMins,
		&i.Status,
		&i.AlertsEnabled,
		&i.MaxAlertsPerIncident,
		&i.ConsecutiveFailures,
		&i.LastCheckedAt,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Keyword,
		&i.KeywordMode,
		&i.KeywordCaseSensitive,
		&i.JsonAssertions,
		&i.MaxResponseTimeMs,
		&i.AlertAfterNFailures,
	)
	return i, err
}
